In [1]:
import pandas as pd
import numpy as np

In [4]:
ls ../..

Invalid switch - "..".

In [10]:
### Get all the pillar names from the excel

In [6]:
names = pd.read_excel('../../UNDP Digital Assessment Data Framework Filename Matching V7.xlsx')

In [7]:
col_names = ['Indicator','check', 'Data Source','Index','Filename']

In [8]:
names = names[col_names]

In [9]:
names.head()

,Indicator,check,Data Source,Index,Filename
0,Countries,NaN,United Nations,False,Countries
1,"Database of Global Administrative Areas (GADM,...",NaN,GADM maps and data,False,NaN
2,High Resolution Population Density Maps + Demo...,NaN,Facebook,False,NaN
3,population density vs openstreetmap object den...,NaN,Kontur,False,NaN
4,Population Density,Infrastructure,World Bank,False,population_density

In [11]:
# get all the files per pillar
data_stats = names.groupby('check').agg({'Filename':'count','Indicator':'count'})

In [17]:
data_stats

                Filename  Indicator
check
Business              20         25
Foundations            9         12
Government            11         15
Infrastructure        46         48
People                38         46
Regulation             6          7
Strategy               1          1

In [20]:
### Infrastructure

In [14]:
bnames = names[(names.check=='Infrastructure')&(~names.Filename.isna())]#&(names.Index==False)]
bnames.head(25)

,Indicator,check,Data Source,Index,Filename
4,Population Density,Infrastructure,World Bank,False,population_density
5,Broadband Density,Infrastructure,World Bank,False,fixed_broadband_density
6,% of population covered by internet connectivity,Infrastructure,World Bank,False,population_access_internet
7,% of population covered by mobile 2G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
8,% of population covered by mobile 3G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
9,% of population covered by mobile 4G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
10,% of population covered by mobile 5G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
11,Mobile Coverage Maps,Infrastructure,GSMA Mobile Connectivity Index,False,mobile_coverage
12,Electricity Density,Infrastructure,Energy Data,False,electricity_yearbook
13,% of population covered by electricity,Infrastructure,World Bank,False,population_electricity_coverage
14,Electricity supply quality,Infrastructure,International Energy Agency / Global Competiti...,False,elect_supply_quality
15,Electricity Environmental Sustainability,Infrastructure,The Sustainable Development Report/ Cambridge ...,False,sustainability_index
16,Electrical Distribution Grid Maps,Infrastructure,Facebook,False,elect_dist_grid_map
17,Cellphone Signal Density,Infrastructure,GSMA Mobile Connectivity Index,False,mobile_density
18,Telecommunication Infrastructure Index (TII),Infrastructure,DESA,True,e_government_index
19,GSMA Mobile Connectivity Index,Infrastructure,GSMA Mobile Connectivity Index,True,countries_mobile_connectivity
20,Spectrum Allocated to Mobile Providers,Infrastructure,GSMA Mobile Connectivity Index,False,spectrum_allocated_mobile_providers
23,Internet Exchange Points (IXPs) map,Infrastructure,Packet Clearing House,False,countries_ixp
24,ISP Speeds - Fixed,Infrastructure,Ookla's Speedtest Intelligence/AWS,False,speedtest-global-performance.yaml
25,ISP Speeds - Mobile,Infrastructure,Ookla's Speedtest Intelligence/AWS,False,speedtest-global-performance.yaml
26,ISP internet download speed average,Infrastructure,Ookla's Speedtest Intelligence,False,internet_speed
27,ISP internet dowload speed at the slowest hour...,Infrastructure,Ookla's Speedtest Intelligence,False,internet_speed
28,Mobile dowload speed at the slowest hour of th...,Infrastructure,GSMA Mobile Connectivity Index,False,mobile_latencies
29,Mobile download speed average,Infrastructure,Ookla's Speedtest Intelligence,False,mobile_speed
30,Individuals using the Internet (% of population),Infrastructure,ITU,False,individual_internet_usage

In [22]:
# get list of names for all indicators
indicators = bnames.Indicator.unique()

In [23]:
# get all file names
bfiles = bnames.Filename.unique()

In [24]:
bfiles

array(['population_density', 'fixed_broadband_density',
       'population_access_internet', 'countries_mobile_connectivity',
       'mobile_coverage', 'electricity_yearbook',
       'population_electricity_coverage', 'elect_supply_quality',
       'sustainability_index', 'elect_dist_grid_map', 'mobile_density',
       'e_government_index', 'spectrum_allocated_mobile_providers',
       'countries_ixp', 'speedtest-global-performance.yaml',
       'internet_speed', 'mobile_latencies', 'mobile_speed',
       'individual_internet_usage', 'mobile_cell_sub',
       'fixed_bdbd_spd_dl_ul',
       'fixed_broadband_speed_download_upload_latency', 'postal_coverage',
       'World Bank The Logistics Performance Index 2007 to 2018.xlsx',
       'schools_w_internet', 'national_cybersecurity_index',
       'dice_export_global_cybersecurity_index',
       'software_developer_ecosystem_size',
       'digital_platform_economy_index', 'migration_skill',
       'migration_industry', 'migration_country',
       'global_fintech_ranking', 'tech_hubs', 'banking_sector_size',
       'angel_investment', 'startup_eco_size',
       'international_co_inventions'], dtype=object)

In [27]:
# formula for converting scale
def convert_rank(old_value, old_min=1, old_max=7, new_min=1, new_max=6 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value

In [44]:
### 2. Broadband Density

In [73]:
indicators[1]

# load data
indicator = indicators[1]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Broadband Density
fixed_broadband_density

FileNotFoundError: [Errno 2] No such file or directory: '../../processed/fixed_broadband_density.csv'

In [ ]:
### 3. % of population covered by internet connectivity

In [47]:
indicators[2]

# load data
indicator = indicators[2]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by internet connectivity
population_access_internet

FileNotFoundError: [Errno 2] No such file or directory: '../../processed/population_access_internet.csv'

In [ ]:
### 4. % of population covered by mobile 2G

In [31]:
indicators[3]

'% of population covered by mobile 2G+ data connectivity'

In [33]:
# load data
indicator = indicators[3]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 2G+ data connectivity
countries_mobile_connectivity

In [51]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [39]:
# filter most recent year
df = df[(df.Year==2019)]

In [40]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [48]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 2G+ data con...,90.00,4.921251,True
11,Angola,2019,% of population covered by mobile 2G+ data con...,90.00,4.921251,True
17,Albania,2019,% of population covered by mobile 2G+ data con...,99.86,5.984898,True
23,United Arab Emirates,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
29,Argentina,2019,% of population covered by mobile 2G+ data con...,98.00,5.784250,True
35,Armenia,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
41,Australia,2019,% of population covered by mobile 2G+ data con...,99.40,5.935275,True
47,Austria,2019,% of population covered by mobile 2G+ data con...,99.00,5.892125,True
53,Azerbaijan,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
59,Burundi,2019,% of population covered by mobile 2G+ data con...,53.65,1.000000,True
65,Belgium,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
71,Benin,2019,% of population covered by mobile 2G+ data con...,98.00,5.784250,True
77,Burkina Faso,2019,% of population covered by mobile 2G+ data con...,97.90,5.773463,True
83,Bangladesh,2019,% of population covered by mobile 2G+ data con...,99.60,5.956850,True
89,Bulgaria,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True

In [49]:
### 5. % of population covered by mobile 3G

In [50]:
indicators[4]

# load data
indicator = indicators[4]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 3G+ data connectivity
countries_mobile_connectivity

In [54]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [55]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['3G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [56]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 3G+ data con...,58.7,3.282895,True
11,Angola,2019,% of population covered by mobile 3G+ data con...,71.0,4.092105,True
17,Albania,2019,% of population covered by mobile 3G+ data con...,97.0,5.802632,True
23,United Arab Emirates,2019,% of population covered by mobile 3G+ data con...,100.0,6.000000,True
29,Argentina,2019,% of population covered by mobile 3G+ data con...,95.0,5.671053,True
35,Armenia,2019,% of population covered by mobile 3G+ data con...,99.0,5.934211,True
41,Australia,2019,% of population covered by mobile 3G+ data con...,99.5,5.967105,True
47,Austria,2019,% of population covered by mobile 3G+ data con...,99.0,5.934211,True
53,Azerbaijan,2019,% of population covered by mobile 3G+ data con...,95.0,5.671053,True
59,Burundi,2019,% of population covered by mobile 3G+ data con...,40.0,2.052632,True
65,Belgium,2019,% of population covered by mobile 3G+ data con...,100.0,6.000000,True
71,Benin,2019,% of population covered by mobile 3G+ data con...,89.0,5.276316,True
77,Burkina Faso,2019,% of population covered by mobile 3G+ data con...,65.0,3.697368,True
83,Bangladesh,2019,% of population covered by mobile 3G+ data con...,95.0,5.671053,True
89,Bulgaria,2019,% of population covered by mobile 3G+ data con...,100.0,6.000000,True

In [57]:
### 6. % of population covered by mobile 4G

In [58]:
indicators[5]

# load data
indicator = indicators[5]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 4G+ data connectivity
countries_mobile_connectivity

In [59]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [60]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['4G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [61]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 4G+ data con...,58.7,3.282895,True
11,Angola,2019,% of population covered by mobile 4G+ data con...,71.0,4.092105,True
17,Albania,2019,% of population covered by mobile 4G+ data con...,97.0,5.802632,True
23,United Arab Emirates,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True
29,Argentina,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
35,Armenia,2019,% of population covered by mobile 4G+ data con...,99.0,5.934211,True
41,Australia,2019,% of population covered by mobile 4G+ data con...,99.5,5.967105,True
47,Austria,2019,% of population covered by mobile 4G+ data con...,99.0,5.934211,True
53,Azerbaijan,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
59,Burundi,2019,% of population covered by mobile 4G+ data con...,40.0,2.052632,True
65,Belgium,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True
71,Benin,2019,% of population covered by mobile 4G+ data con...,89.0,5.276316,True
77,Burkina Faso,2019,% of population covered by mobile 4G+ data con...,65.0,3.697368,True
83,Bangladesh,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
89,Bulgaria,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True

In [62]:
### 7. % of population covered by mobile 5G

In [64]:
indicators[6]

# load data
indicator = indicators[6]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 5G+ data connectivity
countries_mobile_connectivity

In [65]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [66]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['5G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [67]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
11,Angola,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
17,Albania,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
23,United Arab Emirates,2019,% of population covered by mobile 5G+ data con...,100.0,6.0,True
29,Argentina,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
35,Armenia,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
41,Australia,2019,% of population covered by mobile 5G+ data con...,100.0,6.0,True
47,Austria,2019,% of population covered by mobile 5G+ data con...,100.0,6.0,True
53,Azerbaijan,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
59,Burundi,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
65,Belgium,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
71,Benin,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
77,Burkina Faso,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
83,Bangladesh,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True
89,Bulgaria,2019,% of population covered by mobile 5G+ data con...,0.0,1.0,True

In [68]:
### 8. Mobile Coverage Maps

In [69]:
indicators[7]

# load data
indicator = indicators[7]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Mobile Coverage Maps
mobile_coverage

FileNotFoundError: [Errno 2] No such file or directory: '../../processed/mobile_coverage.csv'

In [70]:
### 9. Electricity Density

In [71]:
indicators[8]

# load data
indicator = indicators[8]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Electricity Density
electricity_yearbook

In [72]:
df.head(10)
# Need to update the position of the excel sheet in the data manifest

,Coal and lignite domestic consumption (Mt),Unnamed: 1,data_country,data_year
0,Back to list of tables,NaN,NaN,NaN
1,NaN,2000 - 2017 (%/year),2000 - 2017 (%/year),2000 - 2017 (%/year)
2,World,2.7,2.7,2.7
3,OECD,-1.0,-1.0,-1.0
4,G7,-1.7,-1.7,-1.7
5,BRICS,5.3,5.3,5.3
6,Europe,-0.7,-0.7,-0.7
7,European Union,-1.4,-1.4,-1.4
8,Belgium,-5.6,-5.6,-5.6
9,Czech Rep.,-1.8,-1.8,-1.8

In [74]:
### 10. % of population covered by electricity

In [75]:
indicators[9]

# load data
indicator = indicators[9]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by electricity
population_electricity_coverage

FileNotFoundError: [Errno 2] No such file or directory: '../../processed/population_electricity_coverage.csv'

In [76]:
### 11. % of population covered by electricity

In [77]:
indicators[10]

# load data
indicator = indicators[10]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Electricity supply quality
elect_supply_quality

In [78]:
df.head(10)

,Unnamed: 0,AGO,ALB,ARE,ARG,ARM,AUS,AUT,AZE,BDI,...,GCREURASIA,GCREAP,GCRSASIA,LIC,LMC,UMC,HIC,AVG,data_country,data_year
0,Attribute,Angola,Albania,United Arab Emirates,Argentina,Armenia,Australia,Austria,Azerbaijan,Burundi,...,Eurasia,East Asia and Pacific,South Asia,Low-income,Lower-middle-income,Upper-middle-income,High-income,Sample average,Attribute,Attribute
1,VALUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VALUE,VALUE
2,RANK,136,81,25,83,69,16,21,58,135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,RANK,RANK
3,SCORE,38.11248593,57.61416881,75.00738794,57.20132859,61.27687643,78.74662637,76.60913087,62.71789348,40.25234131,...,59.37969533,69.86862667,54.70460508,43.7445505,51.94942309,59.7912297,72.78080961,60.6396938,SCORE,SCORE
4,DATE DESCRIPTION,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,...,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,2019 edition,DATE DESCRIPTION,DATE DESCRIPTION
5,SOURCE,"World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...",...,"World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...","World Economic Forum, [i]Global Competitivenes...",SOURCE,SOURCE
6,SOURCE DATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SOURCE DATE,SOURCE DATE
7,NOTE,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,See Appendix A of the Global Competitiveness R...,NOTE,NOTE
8,VALUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VALUE,VALUE
9,RANK,136,88,3,109,62,22,20,64,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,RANK,RANK

In [85]:
# The data needs to be transposed as countries are now in columns, not rows, which could present problems for later.

In [80]:
### 12. Electricity Environmental Sustainability

In [83]:
indicators[11]

# load data
indicator = indicators[11]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Electricity Environmental Sustainability
sustainability_index

FileNotFoundError: [Errno 2] No such file or directory: '../../processed/sustainability_index.csv'

In [ ]:
### 13. Electrical Distribution Grid Maps

In [86]:
indicators[12]

# load data
indicator = indicators[12]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Electrical Distribution Grid Maps
elect_dist_grid_map

In [87]:
df.head(10)
#No country names in the data file

        lat       lon  Electrical Distribution Grid
0  6.550017 -8.475952                             1
1  6.604587 -8.475952                             1
2  6.539103 -8.475952                             1
3  6.593674 -8.475952                             1
4  6.560932 -8.442993                             1
5  6.593674 -8.442993                             1
6  6.550017 -8.442993                             1
7  6.550017 -8.453979                             1
8  6.604587 -8.453979                             1
9  6.593674 -8.453979                             1

In [ ]:
### 14. Cellphone Signal Density

In [88]:
indicators[13]

# load data
indicator = indicators[13]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Cellphone Signal Density
mobile_density

In [89]:
df.head(10)

,Unnamed: 0,ISO Code,Country,Region,Year,Network coverage
0,1,AFG,Afghanistan,South Asia,2014,28.919998
1,2,AFG,Afghanistan,South Asia,2015,31.799999
2,3,AFG,Afghanistan,South Asia,2016,33.040001
3,4,AFG,Afghanistan,South Asia,2017,36.340000
4,5,AFG,Afghanistan,South Asia,2018,30.931999
5,6,AFG,Afghanistan,South Asia,2019,38.480000
6,7,AGO,Angola,Sub-Saharan Africa,2014,51.445770
7,8,AGO,Angola,Sub-Saharan Africa,2015,53.906952
8,9,AGO,Angola,Sub-Saharan Africa,2016,61.174950
9,10,AGO,Angola,Sub-Saharan Africa,2017,60.800003

In [90]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Network coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [91]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,Cellphone Signal Density,38.480000,2.117926,True
11,Angola,2019,Cellphone Signal Density,57.400002,3.311828,True
17,Albania,2019,Cellphone Signal Density,87.186005,5.191403,True
23,United Arab Emirates,2019,Cellphone Signal Density,99.599998,5.974759,True
29,Argentina,2019,Cellphone Signal Density,83.708000,4.971932,True
35,Armenia,2019,Cellphone Signal Density,87.599998,5.217527,True
41,Australia,2019,Cellphone Signal Density,99.419998,5.963400,True
47,Austria,2019,Cellphone Signal Density,99.099998,5.943208,True
53,Azerbaijan,2019,Cellphone Signal Density,84.000000,4.990358,True
59,Burundi,2019,Cellphone Signal Density,31.365000,1.668951,True
65,Belgium,2019,Cellphone Signal Density,90.000000,5.368974,True
71,Benin,2019,Cellphone Signal Density,63.399998,3.690444,True
77,Burkina Faso,2019,Cellphone Signal Density,39.245998,2.166263,True
83,Bangladesh,2019,Cellphone Signal Density,79.959999,4.735423,True
89,Bulgaria,2019,Cellphone Signal Density,90.000000,5.368974,True

In [92]:
### 15. Telecommunication Infrastructure Index (TII)

In [122]:
indicators[14]

# load data
indicator = indicators[14]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Telecommunication Infrastructure Index (TII)
e_government_index

In [123]:
df.head(10)

,Survey Year,Country Name,E-Government Rank,E-Government Index,E-Participation Index,Online Service Index,Human Capital Index,Telecommunication Infrastructure Index
0,2020,Iraq,143,0.4360,0.3095,0.3353,0.4358,0.5370
1,2020,Ireland,27,0.8433,0.8571,0.7706,0.9494,0.8100
2,2020,Israel,30,0.8361,0.7143,0.7471,0.8924,0.8689
3,2020,Italy,37,0.8231,0.8214,0.8294,0.8466,0.7932
4,2020,Jamaica,114,0.5392,0.3690,0.3882,0.7142,0.5151
5,2020,Japan,14,0.8989,0.9881,0.9059,0.8684,0.9223
6,2020,Jordan,117,0.5309,0.3333,0.3588,0.6800,0.5540
7,2020,Kazakhstan,29,0.8375,0.8810,0.9235,0.8866,0.7024
8,2020,Kenya,116,0.5326,0.5952,0.6765,0.5812,0.3402
9,2020,Kiribati,145,0.4320,0.5595,0.4941,0.6778,0.1241

In [125]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Telecommunication Infrastructure Index'] 
df['Year'] = df['Survey Year']

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

df.rename(columns={'Country Name':'Country'}, inplace=True)

In [127]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
0,Iraq,2020,Telecommunication Infrastructure Index (TII),0.5370,3.6850,True
1,Ireland,2020,Telecommunication Infrastructure Index (TII),0.8100,5.0500,True
2,Israel,2020,Telecommunication Infrastructure Index (TII),0.8689,5.3445,True
3,Italy,2020,Telecommunication Infrastructure Index (TII),0.7932,4.9660,True
4,Jamaica,2020,Telecommunication Infrastructure Index (TII),0.5151,3.5755,True
5,Japan,2020,Telecommunication Infrastructure Index (TII),0.9223,5.6115,True
6,Jordan,2020,Telecommunication Infrastructure Index (TII),0.5540,3.7700,True
7,Kazakhstan,2020,Telecommunication Infrastructure Index (TII),0.7024,4.5120,True
8,Kenya,2020,Telecommunication Infrastructure Index (TII),0.3402,2.7010,True
9,Kiribati,2020,Telecommunication Infrastructure Index (TII),0.1241,1.6205,True
10,Kuwait,2020,Telecommunication Infrastructure Index (TII),0.7858,4.9290,True
11,Kyrgyzstan,2020,Telecommunication Infrastructure Index (TII),0.5902,3.9510,True
12,Lao People's Democratic Republic,2020,Telecommunication Infrastructure Index (TII),0.2383,2.1915,True
13,Latvia,2020,Telecommunication Infrastructure Index (TII),0.8399,5.1995,True
14,Lebanon,2020,Telecommunication Infrastructure Index (TII),0.4123,3.0615,True

In [ ]:
### 16. GSMA Mobile Connectivity Index

In [112]:
indicators[15]

# load data
indicator = indicators[15]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

GSMA Mobile Connectivity Index
countries_mobile_connectivity

In [113]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [116]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Index'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [117]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,GSMA Mobile Connectivity Index,28.94,2.041533,True
11,Angola,2019,GSMA Mobile Connectivity Index,43.53,2.979555,True
17,Albania,2019,GSMA Mobile Connectivity Index,67.89,4.545712,True
23,United Arab Emirates,2019,GSMA Mobile Connectivity Index,78.23,5.210492,True
29,Argentina,2019,GSMA Mobile Connectivity Index,67.16,4.498778,True
35,Armenia,2019,GSMA Mobile Connectivity Index,56.24,3.796708,True
41,Australia,2019,GSMA Mobile Connectivity Index,90.51,6.000000,True
47,Austria,2019,GSMA Mobile Connectivity Index,84.21,5.594959,True
53,Azerbaijan,2019,GSMA Mobile Connectivity Index,58.28,3.927864,True
59,Burundi,2019,GSMA Mobile Connectivity Index,26.16,1.862801,True
65,Belgium,2019,GSMA Mobile Connectivity Index,82.56,5.488877,True
71,Benin,2019,GSMA Mobile Connectivity Index,39.07,2.692812,True
77,Burkina Faso,2019,GSMA Mobile Connectivity Index,32.44,2.266555,True
83,Bangladesh,2019,GSMA Mobile Connectivity Index,46.47,3.168574,True
89,Bulgaria,2019,GSMA Mobile Connectivity Index,70.37,4.705156,True

In [128]:
### 17. Spectrum Allocated to Mobile Providers

In [129]:
indicators[16]

# load data
indicator = indicators[16]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Spectrum Allocated to Mobile Providers
spectrum_allocated_mobile_providers

In [130]:
df.head(15)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN
10,AGO,Angola,Sub-Saharan Africa,2018,Emerging,42.46,47.61,46.28,47.61,30.98,...,63.34,0.00,40.97,5.39,35.36,57.13,47.25,9.70,NaN,NaN
11,AGO,Angola,Sub-Saharan Africa,2019,Emerging,43.53,48.18,47.65,48.13,32.50,...,57.71,0.77,48.82,6.82,41.20,57.98,46.19,9.70,NaN,NaN
12,ALB,Albania,Europe & Central Asia,2014,Transitioner,53.74,41.32,55.95,74.94,48.13,...,68.42,53.41,44.88,39.75,66.65,60.33,56.55,20.60,NaN,NaN
13,ALB,Albania,Europe & Central Asia,2015,Transitioner,57.42,52.09,54.60,75.56,50.57,...,68.42,57.45,52.15,40.61,65.99,63.29,57.56,24.20,NaN,NaN
14,ALB,Albania,Europe & Central Asia,2016,Transitioner,60.24,57.44,54.45,75.97,55.41,...,67.39,58.70,59.42,48.07,69.64,65.57,65.80,27.80,NaN,NaN

In [132]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Spectrum'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [133]:
df[['Country','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,Spectrum Allocated to Mobile Providers,17.62,1.577685,True
11,Angola,2019,Spectrum Allocated to Mobile Providers,48.22,3.261224,True
17,Albania,2019,Spectrum Allocated to Mobile Providers,52.85,3.515955,True
23,United Arab Emirates,2019,Spectrum Allocated to Mobile Providers,82.44,5.143926,True
29,Argentina,2019,Spectrum Allocated to Mobile Providers,63.38,4.095290,True
35,Armenia,2019,Spectrum Allocated to Mobile Providers,21.43,1.787302,True
41,Australia,2019,Spectrum Allocated to Mobile Providers,75.45,4.759353,True
47,Austria,2019,Spectrum Allocated to Mobile Providers,73.33,4.642716,True
53,Azerbaijan,2019,Spectrum Allocated to Mobile Providers,15.36,1.453345,True
59,Burundi,2019,Spectrum Allocated to Mobile Providers,16.29,1.504511,True
65,Belgium,2019,Spectrum Allocated to Mobile Providers,58.62,3.833407,True
71,Benin,2019,Spectrum Allocated to Mobile Providers,61.31,3.981404,True
77,Burkina Faso,2019,Spectrum Allocated to Mobile Providers,23.82,1.918794,True
83,Bangladesh,2019,Spectrum Allocated to Mobile Providers,19.97,1.706976,True
89,Bulgaria,2019,Spectrum Allocated to Mobile Providers,27.49,2.120709,True

In [134]:
### 18. Internet Exchange Points (IXPs)

In [135]:
indicators[17]

# load data
indicator = indicators[17]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Internet Exchange Points (IXPs) map
countries_ixp

In [149]:
df.head(15)

,Region,Country,City,IXP Name,Participants,Peak,Avg,IPv6,Prefixes,Established,URL,higher_is_better,Number of IXP
0,Asia-Pacific,Afghanistan,Kabul,National Internet Exchange of Afghanistan,20,6.4G,2.19G,NaN,NaN,Jul-18,NaN,True,Internet Exchange Points (IXPs) map
1,Europe,Albania,Tirana,Albanian Neutral Internet eXchange,16,2.42G,35M,NaN,NaN,2018,NaN,True,Internet Exchange Points (IXPs) map
2,NaN,Albania,Tirana,Albania IX,0,NaN,NaN,NaN,NaN,2011,NaN,True,Internet Exchange Points (IXPs) map
3,Africa,Algeria,Algiers,Algeria Internet Exchange,0,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map
4,NaN,Angola,Luanda,Angola Internet Exchange,21,1.6G,NaN,NaN,512.0,17-Mar-06,NaN,True,Internet Exchange Points (IXPs) map
5,NaN,Angola,Luanda,Ponto de Intercambio Internet Angola,0,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map
6,NaN,Angola,Luanda,ANGONIX,21,16G,NaN,NaN,5495.0,9-Mar-15,NaN,True,Internet Exchange Points (IXPs) map
7,Latin America,Argentina,Bahía Blanca,CABASE IXP Bahía Blanca,15,713M,NaN,NaN,NaN,27-Apr-13,NaN,True,Internet Exchange Points (IXPs) map
8,NaN,Argentina,Bariloche,CABASE IXP Bariloche,8,NaN,NaN,NaN,NaN,15-Sep-14,NaN,True,Internet Exchange Points (IXPs) map
9,NaN,Argentina,Buenos Aires,CABASE IXP Buenos Aires,125,9.19G,NaN,NaN,17224.0,1-Apr-98,NaN,True,Internet Exchange Points (IXPs) map
10,NaN,Argentina,Buenos Aires,Cubecorp,0,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map
11,NaN,Argentina,Buenos Aires,CABASE IXP Ruteo Central,0,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map
12,NaN,Argentina,Buenos Aires,CABASE IXP Oeste de Gran Buenos Aires,7,NaN,NaN,NaN,NaN,5-Jul-16,NaN,True,Internet Exchange Points (IXPs) map
13,NaN,Argentina,Buenos Aires,NAP CABASE La Matanza,0,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map
14,NaN,Argentina,Concepcion del Uruguay,CABASE IXP Concepcion del Uruguay,4,NaN,NaN,NaN,NaN,NaN,NaN,True,Internet Exchange Points (IXPs) map

In [150]:
count = df['Country'].value_counts()
count

United States             217
Brazil                     47
Russia                     42
Australia                  39
Germany                    38
                         ...
British Virgin Islands      1
North Macedonia             1
Cuba                        1
Haiti                       1
Azerbaijan                  1
Name: Country, Length: 165, dtype: int64

In [151]:
count = df['Country'].value_counts()

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Spectrum'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

KeyError: 'Spectrum'

In [152]:
### 19. ISP Speeds - Fixed

In [159]:
indicators[18]

# load data
indicator = indicators[18]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

# Convert yaml to csv

ISP Speeds - Fixed
speedtest-global-performance.yaml

AttributeError: module 'pandas' has no attribute 'read_yaml'

In [160]:
df.head(15)

,Region,Country,City,IXP Name,Participants,Peak,Avg,IPv6,Prefixes,Established,URL
0,Asia-Pacific,Afghanistan,Kabul,National Internet Exchange of Afghanistan,20,6.4G,2.19G,NaN,NaN,Jul-18,NaN
1,Europe,Albania,Tirana,Albanian Neutral Internet eXchange,16,2.42G,35M,NaN,NaN,2018,NaN
2,NaN,Albania,Tirana,Albania IX,0,NaN,NaN,NaN,NaN,2011,NaN
3,Africa,Algeria,Algiers,Algeria Internet Exchange,0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Angola,Luanda,Angola Internet Exchange,21,1.6G,NaN,NaN,512.0,17-Mar-06,NaN
5,NaN,Angola,Luanda,Ponto de Intercambio Internet Angola,0,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Angola,Luanda,ANGONIX,21,16G,NaN,NaN,5495.0,9-Mar-15,NaN
7,Latin America,Argentina,Bahía Blanca,CABASE IXP Bahía Blanca,15,713M,NaN,NaN,NaN,27-Apr-13,NaN
8,NaN,Argentina,Bariloche,CABASE IXP Bariloche,8,NaN,NaN,NaN,NaN,15-Sep-14,NaN
9,NaN,Argentina,Buenos Aires,CABASE IXP Buenos Aires,125,9.19G,NaN,NaN,17224.0,1-Apr-98,NaN
10,NaN,Argentina,Buenos Aires,Cubecorp,0,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Argentina,Buenos Aires,CABASE IXP Ruteo Central,0,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Argentina,Buenos Aires,CABASE IXP Oeste de Gran Buenos Aires,7,NaN,NaN,NaN,NaN,5-Jul-16,NaN
13,NaN,Argentina,Buenos Aires,NAP CABASE La Matanza,0,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Argentina,Concepcion del Uruguay,CABASE IXP Concepcion del Uruguay,4,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
### 20. SP Speeds - Mobile

In [162]:
# May also have to convert yaml to csv

In [163]:
### 21. ISP internet download speed average