In [1]:
import pandas as pd
import numpy as np

### Get all the pillar names from the excel

In [2]:
names = pd.read_excel('../../UNDP Digital Assessment Data Framework Filename Matching V7.xlsx')

In [3]:
col_names = ['Indicator','check', 'Data Source','Data Link','Raw/Index','Filename','Sub-Pillar']

In [4]:
names = names[col_names]

In [5]:
names.head()

,Indicator,check,Data Source,Data Link,Raw/Index,Filename,Sub-Pillar
0,Countries,NaN,UN Statistics Division: List of Countries,https://unstats.un.org,Raw,Countries,NaN
1,"Database of Global Administrative Areas (GADM,...",NaN,NaN,https://gadm.org,Raw,NaN,NaN
2,High Resolution Population Density Maps + Demo...,NaN,NaN,NaN,NaN,NaN,NaN
3,population density vs openstreetmap object den...,NaN,NaN,NaN,NaN,NaN,NaN
4,Population Density,Infrastructure,World Bank: World Development Indicators,https://datacatalog.worldbank.org,Raw,population_density,Connectivity Technology

In [6]:
# get all the files per pillar
data_stats = names.groupby('check').agg({'Filename':'count','Indicator':'count'})

In [7]:
data_stats

                Filename  Indicator
check
Business              19         28
Foundations           13         22
Government            11         16
Infrastructure        47         58
People                35         49
Regulation             5          8
Strategy               1          1

### Government

In [8]:
bnames = names[(names.check=='Government')&(~names.Filename.isna())]#&(names.Index==False)]

In [9]:
bnames.head(25)

,Indicator,check,Data Source,Data Link,Raw/Index,Filename,Sub-Pillar
63,Online-Service-Index (OSI),Government,UN: E-Government Survey,https://publicadministration.un.org/egovkb,Index,e_government_index,Digital Public Services
64,E-Participation index,Government,UN: E-Government Survey,https://publicadministration.un.org/egovkb,Index,e_government_index,Digital Public Services
65,Use of public services online (% of services o...,Government,Boston Consulting Group/Salesforce: The Global...,https://www.salesforce.com,Index,digital_public_service_use,Digital Public Services
66,Security incidents (# of relevant issues),Government,SPECOPS,https://specopssoft.com,Raw,cyber_attacks,Digital Public Services
67,Inherent Cyber Risk,Government,FM Global: FM Global Resilience Index,https://www.fmglobal.com/,Index,inherent_cyber_risk,Digital Public Services
68,What is the % change of government digitizing ...,Government,World Bank: GovTech Dataset,https://datacatalog.worldbank.org,Index,Egov_strategy,Digital Public Services
69,R&D spending (% of GDP),Government,World Bank: World Development Indicators,https://datacatalog.worldbank.org,Index,RD_Percentage_GDP,Funding and procurement
70,ICT investment as a percentage of GDP,Government,OECD: Going Digital Toolkit,https://data.oecd.org,Index,ICT_Investment,Funding and procurement
72,Evidence of digital strategies in/across Minis...,Government,World Bank: GovTech Dataset,https://datacatalog.worldbank.org,NaN,Egov_strategy,Funding and procurement
73,Evidence of focus on vulnerable groups,Government,World Bank: GovTech Dataset,https://datacatalog.worldbank.org,NaN,Egov_strategy,Leadership and coordination
76,% of digital skills certifications / training ...,Government,Coursera: Global Skills Reports,https://www.coursera.org/skills-reports/global,Index,digital_skill_level,Capabilities

In [10]:
# get list of names for all indicators
indicators = bnames.Indicator.unique()
subpillars = bnames['Sub-Pillar'].unique()

In [11]:
# get all file names
bfiles = bnames.Filename.unique()

In [12]:
bfiles

array(['e_government_index', 'digital_public_service_use',
       'cyber_attacks', 'inherent_cyber_risk', 'Egov_strategy',
       'RD_Percentage_GDP', 'ICT_Investment', 'digital_skill_level'],
      dtype=object)

In [13]:
subpillars

array(['Digital Public Services', 'Funding and procurement',
       'Leadership and coordination', 'Capabilities'], dtype=object)

In [14]:
# formula for converting scale 0-100
def convert_rank(old_value, old_min=0, old_max=max, new_min=1, new_max=5.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value

In [15]:
# formula for converting scale 0-1
def convert_rank_b(old_value, old_min=0, old_max=1, new_min=1, new_max=5.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value

In [16]:
# formula for converting scale quintile
def convert_rank_I(old_value, old_min,old_max,new_min=1, new_max=1.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value
def convert_rank_II(old_value, old_min, old_max, new_min=2, new_max=2.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value
def convert_rank_III(old_value, old_min, old_max, new_min=3, new_max=3.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value
def convert_rank_IV(old_value, old_min, old_max, new_min=4, new_max=4.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value
def convert_rank_V(old_value, old_min, old_max, new_min=5, new_max=5.99 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value

In [17]:
### Add population dataset
df = pd.read_csv('../../processed/Population.csv')

# Normalize country names as much as possible
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
df['Country Name'] = df['Country Name'].replace('Bahrain (Kingdom of)','Bahrain')
df['Country Name'] = df['Country Name'].replace('Bolivia','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Bolivia, Plurinational State of','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Brunei','Brunei Darussalam')
df['Country Name'] = df['Country Name'].replace('Bulgaria (Rep.)','Bulgaria')
df['Country Name'] = df['Country Name'].replace('Central African Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Central African Rep.','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace("China (People's Rep.)",'China')
df['Country Name'] = df['Country Name'].replace("Comoros",'Comoros (the)')
df['Country Name'] = df['Country Name'].replace("Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Brazzaville)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Rep. of the)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Democratic Republic of the)",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, Dem. Rep.",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, The Democratic Republic of the",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("DR Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of the Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Dem. Rep. of the Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Cote d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Côte d’Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cote D'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cote dIvoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cōte d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Ivory Coast","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Dem. People's Rep. of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Democratic People's Republic of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Korea, Dem. People's Rep.","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("North Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].replace("Eswatini (Kingdom of)",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Swaziland",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Faröe Islands",'Faroe Islands')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
df['Country Name'] = df['Country Name'].replace("Georgia (Country)",'Georgia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
df['Country Name'] = df['Country Name'].replace("Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep. of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep.)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Republic of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea, South",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("South Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Republic of Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace('Republic of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
df['Country Name'] = df['Country Name'].replace("Morroco",'Morocco')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].replace("Niger",'Niger (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
df['Country Name'] = df['Country Name'].replace("West Bank and Gaza",'State of Palestine (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
df['Country Name'] = df['Country Name'].replace("Republic of the Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
df['Country Name'] = df['Country Name'].replace("Russia",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].replace("Russian Federation",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
df['Country Name'] = df['Country Name'].str.replace(r'\bSudan\b', 'Sudan (the)')
df['Country Name'] = df['Country Name'].str.replace(r'\bSudan (the)\b', 'Sudan (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*South Sudan.*$)', "South Sudan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")
df['Country Name'] = df['Country Name'].replace("UAE",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("U.A.E",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("United Arab Emirates",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace('United Kingdom','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('UK','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("Great Britain",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("United Kingdom of Great Britain and Northern Ireland",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('Vietnam','Viet Nam')
df['Country Name'] = df['Country Name'].replace('United States','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('USA','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('United States of America','United States of America (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
df['Country Name'] = df['Country Name'].replace('Sint Maarten','Saint Martin')
df['Country Name'] = df['Country Name'].replace('St. Martin (French part)','Saint Martin (French Part)')
df['Country Name'] = df['Country Name'].replace('Sint Maarten (Dutch part)','Saint Martin (Dutch Part)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
df['Country Name'] = df['Country Name'].replace('Congo, Democratic Republic','Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo, Rep.','Congo (the)')
df['Country Name'] = df['Country Name'].replace('Republic of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo (Rep.)','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
df['Country Name'] = df['Country Name'].replace('Eq. Guinea','Equatorial Guinea')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].replace('C.A. Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Ant.& Barb.','Antigua and Barbuda')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
df['Country Name'] = df['Country Name'].replace('Domin. Rep.','Dominican Republic (the)')
df['Country Name'] = df['Country Name'].replace('Dominica (Commonwealth of)','Dominica')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
df['Country Name'] = df['Country Name'].replace('R. of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].replace('Curacao','Curaçao')
df['Country Name'] = df['Country Name'].replace('Reunion','Réunion')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

pop = df
pop

<ipython-input-17-35a075b1c6b0>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
<ipython-input-17-35a075b1c6b0>:29: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
<ipython-input-17-35a075b1c6b0>:36: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
<ipython-input-17-35a075b1c6b0>:37: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
<ipython-input-17-35a075b1c6b0>:38: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-17-35a075b1c6b0>:39: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-17-35a075b1c6b0>:43: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
<ipython-input-17-35a075b1c6b0>:45: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
<ipython-input-17-35a075b1c6b0>:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
<ipython-input-17-35a075b1c6b0>:55: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
<ipython-input-17-35a075b1c6b0>:56: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
<ipython-input-17-35a075b1c6b0>:57: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
<ipython-input-17-35a075b1c6b0>:58: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
<ipython-input-17-35a075b1c6b0>:59: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
<ipython-input-17-35a075b1c6b0>:60: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
<ipython-input-17-35a075b1c6b0>:62: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
<ipython-input-17-35a075b1c6b0>:63: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-17-35a075b1c6b0>:65: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
<ipython-input-17-35a075b1c6b0>:66: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-17-35a075b1c6b0>:67: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
<ipython-input-17-35a075b1c6b0>:69: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
<ipython-input-17-35a075b1c6b0>:70: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
<ipython-input-17-35a075b1c6b0>:72: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
<ipython-input-17-35a075b1c6b0>:73: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
<ipython-input-17-35a075b1c6b0>:76: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
<ipython-input-17-35a075b1c6b0>:77: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'\bSudan\b', 'Sudan (the)')
<ipython-input-17-35a075b1c6b0>:78: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'\bSudan (the)\b', 'Sudan (the)')
<ipython-input-17-35a075b1c6b0>:79: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*South Sudan.*$)', "South Sudan")
<ipython-input-17-35a075b1c6b0>:80: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
<ipython-input-17-35a075b1c6b0>:81: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
<ipython-input-17-35a075b1c6b0>:82: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
<ipython-input-17-35a075b1c6b0>:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
<ipython-input-17-35a075b1c6b0>:84: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
<ipython-input-17-35a075b1c6b0>:85: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")
<ipython-input-17-35a075b1c6b0>:97: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
<ipython-input-17-35a075b1c6b0>:98: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
<ipython-input-17-35a075b1c6b0>:99: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
<ipython-input-17-35a075b1c6b0>:100: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
<ipython-input-17-35a075b1c6b0>:101: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
<ipython-input-17-35a075b1c6b0>:102: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
<ipython-input-17-35a075b1c6b0>:103: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
<ipython-input-17-35a075b1c6b0>:104: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
<ipython-input-17-35a075b1c6b0>:105: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
<ipython-input-17-35a075b1c6b0>:109: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
<ipython-input-17-35a075b1c6b0>:110: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
<ipython-input-17-35a075b1c6b0>:115: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")
<ipython-input-17-35a075b1c6b0>:116: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
<ipython-input-17-35a075b1c6b0>:117: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
<ipython-input-17-35a075b1c6b0>:118: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
<ipython-input-17-35a075b1c6b0>:119: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
<ipython-input-17-35a075b1c6b0>:120: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
<ipython-input-17-35a075b1c6b0>:121: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
<ipython-input-17-35a075b1c6b0>:123: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
<ipython-input-17-35a075b1c6b0>:126: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
<ipython-input-17-35a075b1c6b0>:129: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
<ipython-input-17-35a075b1c6b0>:131: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
<ipython-input-17-35a075b1c6b0>:132: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
<ipython-input-17-35a075b1c6b0>:133: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
<ipython-input-17-35a075b1c6b0>:136: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2015,2016,2017,2018,2019,2020,Country Name,Country Code,Indicator Name,Indicator Code
0,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,57702.0,58044.0,58377.0,58734.0,...,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,Aruba,ABW,"Population, total",SP.POP.TOTL
1,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,156876454.0,161156430.0,165611760.0,...,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL
2,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,10174840.0,10399936.0,10637064.0,10893772.0,...,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,Afghanistan,AFG,"Population, total",SP.POP.TOTL
3,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,109701811.0,112195950.0,114781116.0,117468741.0,...,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL
4,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,5781305.0,5774440.0,5771973.0,5803677.0,...,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,Angola,AGO,"Population, total",SP.POP.TOTL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,1106000.0,1135000.0,1163000.0,1191000.0,...,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1775378.0,Kosovo (UNSCR 1244),XKX,"Population, total",SP.POP.TOTL
262,5315351.0,5393034.0,5473671.0,5556767.0,5641598.0,5727745.0,5816241.0,5907873.0,6001858.0,6097042.0,...,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,Yemen,YEM,"Population, total",SP.POP.TOTL
263,17099836.0,17524533.0,17965733.0,18423157.0,18896303.0,19384838.0,19888259.0,20406863.0,20942147.0,21496075.0,...,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,South Africa,ZAF,"Population, total",SP.POP.TOTL
264,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,3681953.0,3797877.0,3918872.0,4045740.0,...,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,Zambia,ZMB,"Population, total",SP.POP.TOTL
265,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,4623340.0,4779825.0,4941901.0,5111326.0,...,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL

### 1. Online-Service-Index (OSI)

In [18]:
indicators[0]

'Online-Service-Index (OSI)'

In [19]:
# load data
indicator = indicators[0]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Online-Service-Index (OSI)
e_government_index

In [20]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [21]:
df.head()

,Survey Year,Country Name,E-Government Rank,E-Government Index,E-Participation Index,Online Service Index,Human Capital Index,Telecommunication Infrastructure Index
0,2020,Iraq,143,0.4360,0.3095,0.3353,0.4358,0.5370
1,2020,Ireland,27,0.8433,0.8571,0.7706,0.9494,0.8100
2,2020,Israel,30,0.8361,0.7143,0.7471,0.8924,0.8689
3,2020,Italy,37,0.8231,0.8214,0.8294,0.8466,0.7932
4,2020,Jamaica,114,0.5392,0.3690,0.3882,0.7142,0.5151

In [22]:
# all data from 2020
df['Survey Year'].value_counts()

2020    193
Name: Survey Year, dtype: int64

In [23]:
# score looks like the one to use
df.describe()

,Survey Year,E-Government Rank,E-Government Index,E-Participation Index,Online Service Index,Human Capital Index,Telecommunication Infrastructure Index
count,193.0,193.000000,193.000000,193.000000,193.000000,193.000000,193.000000
mean,2020.0,97.000000,0.598767,0.567723,0.561961,0.687992,0.546354
std,0.0,55.858452,0.214869,0.259592,0.249874,0.194440,0.259358
min,2020.0,1.000000,0.087500,0.000000,0.000000,0.000000,0.000000
25%,2020.0,49.000000,0.432000,0.357100,0.352900,0.559900,0.349600
50%,2020.0,97.000000,0.612900,0.571400,0.576500,0.739500,0.566900
75%,2020.0,145.000000,0.779800,0.797600,0.764700,0.841400,0.772300
max,2020.0,193.000000,0.975800,1.000000,1.000000,1.000000,1.000000

In [24]:
# df.Indicator.unique()

In [25]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Online Service Index'] 
df['Year'] = df['Survey Year']
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_b(row,old_min=0,old_max=1))

In [26]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Iraq,2020,Online-Service-Index (OSI),0.3353,2.673147,True,Digital Public Services
1,Ireland,2020,Online-Service-Index (OSI),0.7706,4.845294,True,Digital Public Services
2,Israel,2020,Online-Service-Index (OSI),0.7471,4.728029,True,Digital Public Services
3,Italy,2020,Online-Service-Index (OSI),0.8294,5.138706,True,Digital Public Services
4,Jamaica,2020,Online-Service-Index (OSI),0.3882,2.937118,True,Digital Public Services
...,...,...,...,...,...,...,...
188,Senegal,2020,Online-Service-Index (OSI),0.4941,3.465559,True,Digital Public Services
189,Serbia,2020,Online-Service-Index (OSI),0.7941,4.962559,True,Digital Public Services
190,Seychelles,2020,Online-Service-Index (OSI),0.6176,4.081824,True,Digital Public Services
191,Singapore,2020,Online-Service-Index (OSI),0.9647,5.813853,True,Digital Public Services
192,Slovakia,2020,Online-Service-Index (OSI),0.7176,4.580824,True,Digital Public Services

In [27]:
# output scores
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator))

## 2. E-Participation index

In [28]:
indicator = indicators[1]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

E-Participation index
e_government_index

In [29]:
df.head()

,Survey Year,Country Name,E-Government Rank,E-Government Index,E-Participation Index,Online Service Index,Human Capital Index,Telecommunication Infrastructure Index
0,2020,Iraq,143,0.4360,0.3095,0.3353,0.4358,0.5370
1,2020,Ireland,27,0.8433,0.8571,0.7706,0.9494,0.8100
2,2020,Israel,30,0.8361,0.7143,0.7471,0.8924,0.8689
3,2020,Italy,37,0.8231,0.8214,0.8294,0.8466,0.7932
4,2020,Jamaica,114,0.5392,0.3690,0.3882,0.7142,0.5151

In [30]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [31]:
df['Survey Year'].unique()

array([2020], dtype=int64)

In [32]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df.iloc[:,4]
df['Year'] = df['Survey Year']
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_b(row,old_min=0,old_max=1))

In [33]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Iraq,2020,E-Participation index,0.3095,2.544405,True,Digital Public Services
1,Ireland,2020,E-Participation index,0.8571,5.276929,True,Digital Public Services
2,Israel,2020,E-Participation index,0.7143,4.564357,True,Digital Public Services
3,Italy,2020,E-Participation index,0.8214,5.098786,True,Digital Public Services
4,Jamaica,2020,E-Participation index,0.3690,2.841310,True,Digital Public Services
...,...,...,...,...,...,...,...
188,Senegal,2020,E-Participation index,0.4405,3.198095,True,Digital Public Services
189,Serbia,2020,E-Participation index,0.8214,5.098786,True,Digital Public Services
190,Seychelles,2020,E-Participation index,0.5714,3.851286,True,Digital Public Services
191,Singapore,2020,E-Participation index,0.9762,5.871238,True,Digital Public Services
192,Slovakia,2020,E-Participation index,0.7024,4.504976,True,Digital Public Services

In [34]:
# output scores
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator))

## 3. Use of public services online (% of services online, penetration, frequency of use)

In [35]:
indicator = indicators[2]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Use of public services online (% of services online, penetration, frequency of use)
digital_public_service_use

In [36]:
# drop first row
df = df.iloc[1: , :]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 1 to 35
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           35 non-null     object
 1   User Satisfaction (%)  35 non-null     float64
dtypes: float64(1), object(1)
memory usage: 692.0+ bytes

In [38]:
df.head(15)

      Country Name  User Satisfaction (%)
1            India                   86.1
2     Saudi Arabia                   84.2
3            China                   81.8
4        Singapore                   80.9
5           France                   79.1
6            Chile                   78.3
7        Hong Kong                   76.6
8            Kenya                   76.1
9           Poland                   75.2
10       Australia                   74.5
11         Estonia                   74.3
12       Indonesia                   73.8
13           Qatar                   72.7
14  United Kingdom                   72.0
15     New Zealand                   71.9

In [39]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [40]:
# create the standard columns
df['higher_is_better'] = True
df['Indicator'] =  indicator
# df['2019 [YR2019]'] = df['2019 [YR2019]'].astype(float)
df['data_col'] = df['User Satisfaction (%)']
df['Year'] = 2020
df['Sub-Pillar'] = subpillar

In [41]:
# convert 1-100 %  into 1-6
min_rank = df['data_col'].min()
max_rank = df['data_col'].max()
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row, old_min=0,old_max=100))

df.sort_values(by='new_rank_score', ascending=False)

# prepare output
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]

# output scores
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator), index=False)

In [42]:
df.head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
1,India,2020,Use of public services online (% of services o...,86.1,5.29639,True,Digital Public Services
2,Saudi Arabia,2020,Use of public services online (% of services o...,84.2,5.20158,True,Digital Public Services
3,China,2020,Use of public services online (% of services o...,81.8,5.08182,True,Digital Public Services
4,Singapore,2020,Use of public services online (% of services o...,80.9,5.03691,True,Digital Public Services
5,France,2020,Use of public services online (% of services o...,79.1,4.94709,True,Digital Public Services
6,Chile,2020,Use of public services online (% of services o...,78.3,4.90717,True,Digital Public Services
7,Hong Kong,2020,Use of public services online (% of services o...,76.6,4.82234,True,Digital Public Services
8,Kenya,2020,Use of public services online (% of services o...,76.1,4.79739,True,Digital Public Services
9,Poland,2020,Use of public services online (% of services o...,75.2,4.75248,True,Digital Public Services
10,Australia,2020,Use of public services online (% of services o...,74.5,4.71755,True,Digital Public Services
11,Estonia,2020,Use of public services online (% of services o...,74.3,4.70757,True,Digital Public Services
12,Indonesia,2020,Use of public services online (% of services o...,73.8,4.68262,True,Digital Public Services
13,Qatar,2020,Use of public services online (% of services o...,72.7,4.62773,True,Digital Public Services
14,United Kingdom,2020,Use of public services online (% of services o...,72.0,4.59280,True,Digital Public Services
15,New Zealand,2020,Use of public services online (% of services o...,71.9,4.58781,True,Digital Public Services

## 4. Security incidents (# of relevant issues)

In [43]:
indicator = indicators[3]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Security incidents (# of relevant issues)
cyber_attacks

In [44]:
df.head()

          Country  Number of Significant Cyberattacks (2006-2020)
0   United States                                             156
1  United Kingdom                                              47
2           India                                              23
3         Germany                                              21
4     South Korea                                              18

In [45]:
# create a rank from the number of attacks fields
df['data_rank'] = df['Number of Significant Cyberattacks (2006-2020)'].rank(method='max')

In [46]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [47]:
# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = False
df['Indicator'] = indicator
df['data_col'] = df['data_rank']
df['Year'] = 2020
df['Sub-Pillar'] = subpillar

In [48]:
df = df[['Country Name', 'Year','Indicator','data_col','higher_is_better','Sub-Pillar']]

# Normalize country names as much as possible
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
df['Country Name'] = df['Country Name'].replace('Bahrain (Kingdom of)','Bahrain')
df['Country Name'] = df['Country Name'].replace('Bolivia','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Bolivia, Plurinational State of','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Brunei','Brunei Darussalam')
df['Country Name'] = df['Country Name'].replace('Bulgaria (Rep.)','Bulgaria')
df['Country Name'] = df['Country Name'].replace('Central African Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Central African Rep.','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace("China (People's Rep.)",'China')
df['Country Name'] = df['Country Name'].replace("Comoros",'Comoros (the)')
df['Country Name'] = df['Country Name'].replace("Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Brazzaville)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Rep. of the)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Democratic Republic of the)",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, Dem. Rep.",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, The Democratic Republic of the",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("DR Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of the Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Dem. Rep. of the Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Cote d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Côte d’Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cote D'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cote dIvoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cōte d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Ivory Coast","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Dem. People's Rep. of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Democratic People's Republic of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Korea, Dem. People's Rep.","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("North Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].replace("Eswatini (Kingdom of)",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Swaziland",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Faröe Islands",'Faroe Islands')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
df['Country Name'] = df['Country Name'].replace("Georgia (Country)",'Georgia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
df['Country Name'] = df['Country Name'].replace("Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep. of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep.)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Republic of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea, South",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("South Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Republic of Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace('Republic of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
df['Country Name'] = df['Country Name'].replace("Morroco",'Morocco')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].replace("Niger",'Niger (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
df['Country Name'] = df['Country Name'].replace("West Bank and Gaza",'State of Palestine (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
df['Country Name'] = df['Country Name'].replace("Republic of the Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
df['Country Name'] = df['Country Name'].replace("Russia",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].replace("Russian Federation",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
df['Country Name'] = df['Country Name'].str.replace(r'\bSudan\b', 'Sudan (the)')
df['Country Name'] = df['Country Name'].str.replace(r'\bSudan (the)\b', 'Sudan (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*South Sudan.*$)', "South Sudan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")
df['Country Name'] = df['Country Name'].replace("UAE",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("U.A.E",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("United Arab Emirates",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace('United Kingdom','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('UK','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("Great Britain",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("United Kingdom of Great Britain and Northern Ireland",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('Vietnam','Viet Nam')
df['Country Name'] = df['Country Name'].replace('United States','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('USA','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('United States of America','United States of America (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
df['Country Name'] = df['Country Name'].replace('Sint Maarten','Saint Martin')
df['Country Name'] = df['Country Name'].replace('St. Martin (French part)','Saint Martin (French Part)')
df['Country Name'] = df['Country Name'].replace('Sint Maarten (Dutch part)','Saint Martin (Dutch Part)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
df['Country Name'] = df['Country Name'].replace('Congo, Democratic Republic','Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo, Rep.','Congo (the)')
df['Country Name'] = df['Country Name'].replace('Republic of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo (Rep.)','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
df['Country Name'] = df['Country Name'].replace('Eq. Guinea','Equatorial Guinea')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].replace('C.A. Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Ant.& Barb.','Antigua and Barbuda')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
df['Country Name'] = df['Country Name'].replace('Domin. Rep.','Dominican Republic (the)')
df['Country Name'] = df['Country Name'].replace('Dominica (Commonwealth of)','Dominica')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
df['Country Name'] = df['Country Name'].replace('R. of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].replace('Curacao','Curaçao')
df['Country Name'] = df['Country Name'].replace('Reunion','Réunion')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

df

<ipython-input-48-e45f714368bd>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
<ipython-input-48-e45f714368bd>:28: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
<ipython-input-48-e45f714368bd>:35: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
<ipython-input-48-e45f714368bd>:36: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
<ipython-input-48-e45f714368bd>:37: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-48-e45f714368bd>:38: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-48-e45f714368bd>:42: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
<ipython-input-48-e45f714368bd>:44: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
<ipython-input-48-e45f714368bd>:49: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
<ipython-input-48-e45f714368bd>:54: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
<ipython-input-48-e45f714368bd>:55: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
<ipython-input-48-e45f714368bd>:56: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
<ipython-input-48-e45f714368bd>:57: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
<ipython-input-48-e45f714368bd>:58: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
<ipython-input-48-e45f714368bd>:59: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
<ipython-input-48-e45f714368bd>:61: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
<ipython-input-48-e45f714368bd>:62: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-48-e45f714368bd>:64: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
<ipython-input-48-e45f714368bd>:65: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-48-e45f714368bd>:66: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
<ipython-input-48-e45f714368bd>:68: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
<ipython-input-48-e45f714368bd>:69: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
<ipython-input-48-e45f714368bd>:71: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
<ipython-input-48-e45f714368bd>:72: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
<ipython-input-48-e45f714368bd>:75: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
<ipython-input-48-e45f714368bd>:76: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'\bSudan\b', 'Sudan (the)')
<ipython-input-48-e45f714368bd>:77: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'\bSudan (the)\b', 'Sudan (the)')
<ipython-input-48-e45f714368bd>:78: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*South Sudan.*$)', "South Sudan")
<ipython-input-48-e45f714368bd>:79: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
<ipython-input-48-e45f714368bd>:80: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
<ipython-input-48-e45f714368bd>:81: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
<ipython-input-48-e45f714368bd>:82: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
<ipython-input-48-e45f714368bd>:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
<ipython-input-48-e45f714368bd>:84: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")
<ipython-input-48-e45f714368bd>:96: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
<ipython-input-48-e45f714368bd>:97: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
<ipython-input-48-e45f714368bd>:98: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
<ipython-input-48-e45f714368bd>:99: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
<ipython-input-48-e45f714368bd>:100: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
<ipython-input-48-e45f714368bd>:101: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
<ipython-input-48-e45f714368bd>:102: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
<ipython-input-48-e45f714368bd>:103: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
<ipython-input-48-e45f714368bd>:104: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
<ipython-input-48-e45f714368bd>:108: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
<ipython-input-48-e45f714368bd>:109: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
<ipython-input-48-e45f714368bd>:114: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")
<ipython-input-48-e45f714368bd>:115: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
<ipython-input-48-e45f714368bd>:116: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
<ipython-input-48-e45f714368bd>:117: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
<ipython-input-48-e45f714368bd>:118: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
<ipython-input-48-e45f714368bd>:119: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
<ipython-input-48-e45f714368bd>:120: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
<ipython-input-48-e45f714368bd>:122: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
<ipython-input-48-e45f714368bd>:125: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
<ipython-input-48-e45f714368bd>:128: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
<ipython-input-48-e45f714368bd>:130: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
<ipython-input-48-e45f714368bd>:131: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
<ipython-input-48-e45f714368bd>:132: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
<ipython-input-48-e45f714368bd>:135: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

,Country Name,Year,Indicator,data_col,higher_is_better,Sub-Pillar
0,United States of America (the),2020,Security incidents (# of relevant issues),20.0,False,Digital Public Services
1,United Kingdom of Great Britain and Northern I...,2020,Security incidents (# of relevant issues),19.0,False,Digital Public Services
2,India,2020,Security incidents (# of relevant issues),18.0,False,Digital Public Services
3,Germany,2020,Security incidents (# of relevant issues),17.0,False,Digital Public Services
4,Republic of Korea (the),2020,Security incidents (# of relevant issues),16.0,False,Digital Public Services
5,Australia,2020,Security incidents (# of relevant issues),15.0,False,Digital Public Services
6,Ukraine,2020,Security incidents (# of relevant issues),15.0,False,Digital Public Services
7,China,2020,Security incidents (# of relevant issues),13.0,False,Digital Public Services
8,Iran (Islamic Republic of),2020,Security incidents (# of relevant issues),13.0,False,Digital Public Services
9,Saudi Arabia,2020,Security incidents (# of relevant issues),13.0,False,Digital Public Services
10,Japan,2020,Security incidents (# of relevant issues),10.0,False,Digital Public Services
11,Canada,2020,Security incidents (# of relevant issues),9.0,False,Digital Public Services
12,France,2020,Security incidents (# of relevant issues),8.0,False,Digital Public Services
13,Israel,2020,Security incidents (# of relevant issues),8.0,False,Digital Public Services
14,Pakistan,2020,Security incidents (# of relevant issues),6.0,False,Digital Public Services
15,Russian Federation (the),2020,Security incidents (# of relevant issues),5.0,False,Digital Public Services
16,"China, Hong Kong Special Administrative Region",2020,Security incidents (# of relevant issues),4.0,False,Digital Public Services
17,Viet Nam,2020,Security incidents (# of relevant issues),3.0,False,Digital Public Services
18,Turkey,2020,Security incidents (# of relevant issues),3.0,False,Digital Public Services
19,Democratic People's Republic of Korea (the),2020,Security incidents (# of relevant issues),1.0,False,Digital Public Services

In [49]:
df=df.merge(pop,how='outer',on='Country Name')
# Calculate the number of incidents per 1,000,000 people
df['new_data_col'] = df['data_col']/df['2020']*1000000
df=df[df['Indicator'].notna()]
df=df[['Country Name','Year','Indicator','new_data_col','higher_is_better','Sub-Pillar']]

min_rank = df['new_data_col'].min()
max_rank = df['new_data_col'].max()

In [50]:
first = df['new_data_col'].quantile(1/5)
second = df['new_data_col'].quantile(2/5)
third = df['new_data_col'].quantile(3/5)
fourth = df['new_data_col'].quantile(4/5)
fifth = df['new_data_col'].quantile(5/5)
data = {'Min':min_rank,'Max':max_rank,'1':first,'2':second,'3':third,'4':fourth,'5':fifth}
sextile = pd.DataFrame(data, index=[0])
sextile

        Min       Max         1         2        3         4         5
0  0.009272  0.867971  0.033922  0.071961  0.21726  0.346578  0.867971

In [51]:
df.rename(columns={'new_data_col':'data_col'}, inplace=True)
min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

df.loc[df['data_col'] <= first, 'new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_I(row, old_min=min_rank,old_max=first))
df.loc[(df['data_col'] > first) & (df['data_col'] <= second), 'new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_II(row, old_min=first,old_max=second))
df.loc[(df['data_col'] > second) & (df['data_col'] <= third), 'new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_III(row, old_min=second,old_max=third))
df.loc[(df['data_col'] > third) & (df['data_col'] <= fourth), 'new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_IV(row, old_min=third,old_max=fourth))
df.loc[df['data_col'] > fourth, 'new_rank_score'] = df['data_col'].apply(lambda row: convert_rank_V(row, old_min=fourth,old_max=max_rank))

df['new_rank_score'] = df['new_rank_score'].apply(lambda row: (5.99-row)+1)
df=df[df['new_rank_score'].notna()]
df

,Country Name,Year,Indicator,data_col,higher_is_better,Sub-Pillar,new_rank_score
0,United States of America (the),2020.0,Security incidents (# of relevant issues),0.060701,False,Digital Public Services,4.293060
1,United Kingdom of Great Britain and Northern I...,2020.0,Security incidents (# of relevant issues),0.282674,False,Digital Public Services,2.489222
2,India,2020.0,Security incidents (# of relevant issues),0.013043,False,Digital Public Services,5.838520
3,Germany,2020.0,Security incidents (# of relevant issues),0.204227,False,Digital Public Services,3.088800
4,Republic of Korea (the),2020.0,Security incidents (# of relevant issues),0.308996,False,Digital Public Services,2.287709
5,Australia,2020.0,Security incidents (# of relevant issues),0.583952,False,Digital Public Services,1.539283
6,Ukraine,2020.0,Security incidents (# of relevant issues),0.339869,False,Digital Public Services,2.051362
7,China,2020.0,Security incidents (# of relevant issues),0.009272,False,Digital Public Services,5.990000
8,Iran (Islamic Republic of),2020.0,Security incidents (# of relevant issues),0.154775,False,Digital Public Services,3.425747
9,Saudi Arabia,2020.0,Security incidents (# of relevant issues),0.373414,False,Digital Public Services,1.939044
10,Japan,2020.0,Security incidents (# of relevant issues),0.079469,False,Digital Public Services,3.938851
11,Canada,2020.0,Security incidents (# of relevant issues),0.236809,False,Digital Public Services,2.840340
12,France,2020.0,Security incidents (# of relevant issues),0.118709,False,Digital Public Services,3.671482
13,Israel,2020.0,Security incidents (# of relevant issues),0.867971,False,Digital Public Services,1.000000
14,Pakistan,2020.0,Security incidents (# of relevant issues),0.027163,False,Digital Public Services,5.271465
15,Russian Federation (the),2020.0,Security incidents (# of relevant issues),0.034697,False,Digital Public Services,4.969820
16,"China, Hong Kong Special Administrative Region",2020.0,Security incidents (# of relevant issues),0.534631,False,Digital Public Services,1.632933
17,Viet Nam,2020.0,Security incidents (# of relevant issues),0.030820,False,Digital Public Services,5.124564
18,Turkey,2020.0,Security incidents (# of relevant issues),0.035571,False,Digital Public Services,4.947086
19,Democratic People's Republic of Korea (the),2020.0,Security incidents (# of relevant issues),0.038792,False,Digital Public Services,4.863262

In [52]:
# # output scores
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator), index=False)
df.to_csv('../non-index/government_{}_scores.csv'.format(indicator), index=False)

In [53]:
## 5. Inherent Cyber Risk

In [54]:
indicator = indicators[4]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Inherent Cyber Risk
inherent_cyber_risk

In [55]:
df.head()

     Country  Inherent Cyber Risk
0    Albania                 55.0
1    Algeria                 48.9
2  Argentina                 61.7
3    Armenia                 46.3
4  Australia                 63.5

In [56]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [57]:
# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df.iloc[:,1]
df['Year'] = 2021
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=0,old_max=100))

In [58]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Albania,2021,Inherent Cyber Risk,55.0,3.74450,True,Digital Public Services
1,Algeria,2021,Inherent Cyber Risk,48.9,3.44011,True,Digital Public Services
2,Argentina,2021,Inherent Cyber Risk,61.7,4.07883,True,Digital Public Services
3,Armenia,2021,Inherent Cyber Risk,46.3,3.31037,True,Digital Public Services
4,Australia,2021,Inherent Cyber Risk,63.5,4.16865,True,Digital Public Services
...,...,...,...,...,...,...,...
121,Uruguay,2021,Inherent Cyber Risk,69.6,4.47304,True,Digital Public Services
122,Venezuela,2021,Inherent Cyber Risk,29.6,2.47704,True,Digital Public Services
123,Vietnam,2021,Inherent Cyber Risk,36.4,2.81636,True,Digital Public Services
124,Zambia,2021,Inherent Cyber Risk,80.7,5.02693,True,Digital Public Services
125,Zimbabwe,2021,Inherent Cyber Risk,62.9,4.13871,True,Digital Public Services

## 6. What is the % change of government digitizing public services?

In [59]:
indicator = indicators[5]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

What is the % change of government digitizing public services?
Egov_strategy

In [60]:
df.head()

,#,Flag,Code,Cnum,Economy,Level,Population,GNI,GNIPC,e-Government,...,NGTI-1,NGTI-2,NGTI-3,NGTI-4,GTI-1,GTI-2,GTI-3,GTI-4,data_country,data_year
0,1,NaN,AFG,4.0,Afghanistan,LIC,"38,928","20,726",540,https://mcit.gov.af/node/6938,...,0.69,0.52,0.31,0.62,-0.09,-0.34,0.02,-0.12,NaN,NaN
1,2,NaN,ALB,8.0,Albania,UMIC,"2,878","14,949","5,240",https://e-albania.al/,...,0.81,0.78,0.60,0.77,0.29,0.62,0.74,0.26,NaN,NaN
2,3,NaN,DZA,12.0,Algeria,LMIC,"43,851","170,722","3,970",https://www.mpttn.gov.dz/ar/content/%D8%A7%D9%...,...,0.73,0.46,0.02,0.60,0.06,-0.56,-0.68,-0.15,NaN,NaN
3,4,NaN,ADO,20.0,Andorra,HIC,77,"3,154","40,886",http://www.govern.ad,...,0.63,0.60,0.05,0.13,-0.28,-0.06,-0.62,-1.32,NaN,NaN
4,5,NaN,AGO,24.0,Angola,LMIC,"32,866","97,005","3,050",http://www.governo.gov.ao,...,0.68,0.69,0.21,0.61,-0.12,0.27,-0.23,-0.13,NaN,NaN

In [61]:
# Must limit the database to the first 206 rows, the remaining rows do not contain any useful information
df = df.iloc[0:205,:]

# Drop the superfluous rows by dropping na
df = df[pd.to_numeric(df['#'], errors='coerce').notnull()]
df['#'] = df[df['#'].notna()]

# Must convert data in the DPL column into float
df['CGSI'] = df['CGSI'].replace('-',np.nan)
df['CGSI'] = df['CGSI'].astype(float, errors = 'ignore')

In [62]:
subpillars[0]
subpillar = subpillars[0]
print(subpillar)

Digital Public Services

In [63]:
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['CGSI']
df['Country Name'] = df['Economy']
df['Year'] = 2020
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [64]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df.head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Afghanistan,2020,What is the % change of government digitizing ...,0.69,4.513367,True,Digital Public Services
1,Albania,2020,What is the % change of government digitizing ...,0.79,5.022551,True,Digital Public Services
2,Algeria,2020,What is the % change of government digitizing ...,0.71,4.615204,True,Digital Public Services
3,Andorra,2020,What is the % change of government digitizing ...,0.58,3.953265,True,Digital Public Services
4,Angola,2020,What is the % change of government digitizing ...,0.67,4.411531,True,Digital Public Services
5,Antigua and Barbuda,2020,What is the % change of government digitizing ...,0.68,4.462449,True,Digital Public Services
6,Argentina,2020,What is the % change of government digitizing ...,0.81,5.124388,True,Digital Public Services
7,Armenia,2020,What is the % change of government digitizing ...,0.73,4.717041,True,Digital Public Services
8,Australia,2020,What is the % change of government digitizing ...,0.89,5.531735,True,Digital Public Services
9,Austria,2020,What is the % change of government digitizing ...,NaN,NaN,True,Digital Public Services
11,Azerbaijan,2020,What is the % change of government digitizing ...,0.76,4.869796,True,Digital Public Services
12,Bahamas,2020,What is the % change of government digitizing ...,0.72,4.666122,True,Digital Public Services
13,Bahrain,2020,What is the % change of government digitizing ...,0.59,4.004184,True,Digital Public Services
14,Bangladesh,2020,What is the % change of government digitizing ...,0.81,5.124388,True,Digital Public Services
15,Barbados,2020,What is the % change of government digitizing ...,0.75,4.818878,True,Digital Public Services

In [65]:
# output scores

In [66]:
## 7. R&D spending (% of GDP)

In [67]:
indicator = indicators[6]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

R&D spending (% of GDP)
RD_Percentage_GDP

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   1960            0 non-null      float64
 1   1961            0 non-null      float64
 2   1962            0 non-null      float64
 3   1963            0 non-null      float64
 4   1964            0 non-null      float64
 5   1965            0 non-null      float64
 6   1966            0 non-null      float64
 7   1967            0 non-null      float64
 8   1968            0 non-null      float64
 9   1969            0 non-null      float64
 10  1970            0 non-null      float64
 11  1971            0 non-null      float64
 12  1972            0 non-null      float64
 13  1973            0 non-null      float64
 14  1974            0 non-null      float64
 15  1975            0 non-null      float64
 16  1976            0 non-null      float64
 17  1977            0 non-null      float64
 18  1978            0 non-null      float64
 19  1979            0 non-null      float64
 20  1980            0 non-null      float64
 21  1981            0 non-null      float64
 22  1982            0 non-null      float64
 23  1983            0 non-null      float64
 24  1984            0 non-null      float64
 25  1985            0 non-null      float64
 26  1986            0 non-null      float64
 27  1987            0 non-null      float64
 28  1988            0 non-null      float64
 29  1989            0 non-null      float64
 30  1990            0 non-null      float64
 31  1991            0 non-null      float64
 32  1992            0 non-null      float64
 33  1993            0 non-null      float64
 34  1994            0 non-null      float64
 35  1995            0 non-null      float64
 36  1996            70 non-null     float64
 37  1997            88 non-null     float64
 38  1998            83 non-null     float64
 39  1999            85 non-null     float64
 40  2000            100 non-null    float64
 41  2001            110 non-null    float64
 42  2002            124 non-null    float64
 43  2003            117 non-null    float64
 44  2004            118 non-null    float64
 45  2005            116 non-null    float64
 46  2006            108 non-null    float64
 47  2007            124 non-null    float64
 48  2008            118 non-null    float64
 49  2009            116 non-null    float64
 50  2010            113 non-null    float64
 51  2011            112 non-null    float64
 52  2012            113 non-null    float64
 53  2013            122 non-null    float64
 54  2014            116 non-null    float64
 55  2015            129 non-null    float64
 56  2016            116 non-null    float64
 57  2017            121 non-null    float64
 58  2018            108 non-null    float64
 59  2019            2 non-null      float64
 60  2020            0 non-null      float64
 61  Country Name    266 non-null    object
 62  Country Code    266 non-null    object
 63  Indicator Name  266 non-null    object
 64  Indicator Code  266 non-null    object
 65  data_country    0 non-null      float64
 66  data_year       0 non-null      float64
dtypes: float64(63), object(4)
memory usage: 139.4+ KB

In [69]:
subpillars[1]
subpillar = subpillars[1]
print(subpillar)

Funding and procurement

In [70]:
df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2017,2018,2019,2020,Country Name,Country Code,Indicator Name,Indicator Code,data_country,data_year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Aruba,ABW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Africa Eastern and Southern,AFE,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Afghanistan,AFG,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Africa Western and Central,AFW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Angola,AGO,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN

In [71]:
# create standard columns
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2018'] 
df['Sub-Pillar'] = subpillar
df['Year'] = 2018

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=0,old_max=100))

In [72]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Aruba,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
1,Africa Eastern and Southern,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
2,Afghanistan,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
3,Africa Western and Central,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
4,Angola,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
...,...,...,...,...,...,...,...
261,Kosovo,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
262,"Yemen, Rep.",2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
263,South Africa,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
264,Zambia,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement
265,Zimbabwe,2018,R&D spending (% of GDP),NaN,NaN,True,Funding and procurement

In [73]:
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator), index=False)

## 8. ICT investment as a percentage of GDP

In [74]:
indicator = indicators[7]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

ICT investment as a percentage of GDP
ICT_Investment

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  450 non-null    object
 1   INDICATOR     450 non-null    object
 2   SUBJECT       450 non-null    object
 3   MEASURE       450 non-null    object
 4   FREQUENCY     450 non-null    object
 5   TIME          450 non-null    int64
 6   Value         450 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 24.7+ KB

In [76]:
df.head()

  Country Name INDICATOR SUBJECT MEASURE FREQUENCY  TIME      Value
0    Australia  ICTINVST     TOT      PC         A  1985  12.465454
1    Australia  ICTINVST     TOT      PC         A  1986  13.939533
2    Australia  ICTINVST     TOT      PC         A  1987  14.142429
3    Australia  ICTINVST     TOT      PC         A  1988  14.289993
4    Australia  ICTINVST     TOT      PC         A  1989  15.348707

In [77]:
df.SUBJECT.unique()

array(['TOT'], dtype=object)

In [78]:
df.TIME.max()

2010

In [79]:
df.Value.describe()

count    450.000000
mean      16.074272
std        5.636379
min        2.798417
25%       12.410442
50%       14.840726
75%       19.419433
max       32.601105
Name: Value, dtype: float64

In [80]:
subpillars[1]
subpillar = subpillars[1]
print(subpillar)

Funding and procurement

In [81]:
dcol = 'Value'
indicol = indicator
cname = 'Country Name'

# filter most recent year
df = df[(df.TIME==2010)]

# create standard columns
df['higher_is_better'] = True
df['Indicator'] =  indicator
df['Country Name'] = df[cname]
# # df['2019 [YR2019]'] = df['2019 [YR2019]'].astype(float)
df['data_col'] = df[dcol]
df['Sub-Pillar'] = subpillar
df['Year'] = 2010

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 1-20 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=0,old_max=100))

# df.sort_values(by='new_rank_score', ascending=False)

# # prepare output
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]

# # output scores
df.to_csv('../indicator_scores/government_{}_scores.csv'.format(indicator), index=False)

In [82]:
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
72,Canada,2010,ICT investment as a percentage of GDP,17.018367,1.849217,True,Funding and procurement
121,Finland,2010,ICT investment as a percentage of GDP,15.519828,1.774439,True,Funding and procurement
172,Germany,2010,ICT investment as a percentage of GDP,12.690394,1.633251,True,Funding and procurement
198,Ireland,2010,ICT investment as a percentage of GDP,12.412805,1.619399,True,Funding and procurement
224,Italy,2010,ICT investment as a percentage of GDP,11.026056,1.550200,True,Funding and procurement
274,Republic of Korea (the),2010,ICT investment as a percentage of GDP,10.716026,1.534730,True,Funding and procurement
323,New Zealand,2010,ICT investment as a percentage of GDP,21.238183,2.059785,True,Funding and procurement
349,Spain,2010,ICT investment as a percentage of GDP,13.763415,1.686794,True,Funding and procurement
400,Switzerland,2010,ICT investment as a percentage of GDP,18.506691,1.923484,True,Funding and procurement
449,United States of America (the),2010,ICT investment as a percentage of GDP,32.137836,2.603678,True,Funding and procurement

## 9. Evidence of digital strategies in/across Ministries

In [83]:
indicator = indicators[8]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Evidence of digital strategies in/across Ministries
Egov_strategy

In [84]:
df.head()

,#,Flag,Code,Cnum,Economy,Level,Population,GNI,GNIPC,e-Government,...,NGTI-1,NGTI-2,NGTI-3,NGTI-4,GTI-1,GTI-2,GTI-3,GTI-4,data_country,data_year
0,1,NaN,AFG,4.0,Afghanistan,LIC,"38,928","20,726",540,https://mcit.gov.af/node/6938,...,0.69,0.52,0.31,0.62,-0.09,-0.34,0.02,-0.12,NaN,NaN
1,2,NaN,ALB,8.0,Albania,UMIC,"2,878","14,949","5,240",https://e-albania.al/,...,0.81,0.78,0.60,0.77,0.29,0.62,0.74,0.26,NaN,NaN
2,3,NaN,DZA,12.0,Algeria,LMIC,"43,851","170,722","3,970",https://www.mpttn.gov.dz/ar/content/%D8%A7%D9%...,...,0.73,0.46,0.02,0.60,0.06,-0.56,-0.68,-0.15,NaN,NaN
3,4,NaN,ADO,20.0,Andorra,HIC,77,"3,154","40,886",http://www.govern.ad,...,0.63,0.60,0.05,0.13,-0.28,-0.06,-0.62,-1.32,NaN,NaN
4,5,NaN,AGO,24.0,Angola,LMIC,"32,866","97,005","3,050",http://www.governo.gov.ao,...,0.68,0.69,0.21,0.61,-0.12,0.27,-0.23,-0.13,NaN,NaN

In [85]:
# Must limit the database to the first 206 rows, the remaining rows do not contain any useful information
df = df.iloc[0:205,:]

# Drop the superfluous rows by dropping na
df = df[pd.to_numeric(df['#'], errors='coerce').notnull()]
df['#'] = df[df['#'].notna()]

# Must convert data in the DPL column into float
df['DG St'] = df['DG St'].replace('-',np.nan)
df['DG St'] = df['DG St'].astype(float, errors = 'ignore')

In [86]:
subpillars[1]
subpillar = subpillars[1]
print(subpillar)

Funding and procurement

In [87]:
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['DG St']
df['Country Name'] = df['Economy']
df['Year'] = 2020
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

max_rank

3.0

In [88]:
# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [89]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df.head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Afghanistan,2020,Evidence of digital strategies in/across Minis...,2.0,4.326667,True,Funding and procurement
1,Albania,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
2,Algeria,2020,Evidence of digital strategies in/across Minis...,2.0,4.326667,True,Funding and procurement
3,Andorra,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
4,Angola,2020,Evidence of digital strategies in/across Minis...,2.0,4.326667,True,Funding and procurement
5,Antigua and Barbuda,2020,Evidence of digital strategies in/across Minis...,1.0,2.663333,True,Funding and procurement
6,Argentina,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
7,Armenia,2020,Evidence of digital strategies in/across Minis...,1.0,2.663333,True,Funding and procurement
8,Australia,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
9,Austria,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
11,Azerbaijan,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
12,Bahamas,2020,Evidence of digital strategies in/across Minis...,1.0,2.663333,True,Funding and procurement
13,Bahrain,2020,Evidence of digital strategies in/across Minis...,2.0,4.326667,True,Funding and procurement
14,Bangladesh,2020,Evidence of digital strategies in/across Minis...,3.0,5.990000,True,Funding and procurement
15,Barbados,2020,Evidence of digital strategies in/across Minis...,2.0,4.326667,True,Funding and procurement

In [90]:
# # output scores

## 10. Evidence of focus on vulnerable groups

In [91]:
indicator = indicators[9]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

df = df.iloc[1:,:]

Evidence of focus on vulnerable groups
Egov_strategy

In [92]:
df.head()

,#,Flag,Code,Cnum,Economy,Level,Population,GNI,GNIPC,e-Government,...,NGTI-1,NGTI-2,NGTI-3,NGTI-4,GTI-1,GTI-2,GTI-3,GTI-4,data_country,data_year
1,2,NaN,ALB,8.0,Albania,UMIC,"2,878","14,949","5,240",https://e-albania.al/,...,0.81,0.78,0.60,0.77,0.29,0.62,0.74,0.26,NaN,NaN
2,3,NaN,DZA,12.0,Algeria,LMIC,"43,851","170,722","3,970",https://www.mpttn.gov.dz/ar/content/%D8%A7%D9%...,...,0.73,0.46,0.02,0.60,0.06,-0.56,-0.68,-0.15,NaN,NaN
3,4,NaN,ADO,20.0,Andorra,HIC,77,"3,154","40,886",http://www.govern.ad,...,0.63,0.60,0.05,0.13,-0.28,-0.06,-0.62,-1.32,NaN,NaN
4,5,NaN,AGO,24.0,Angola,LMIC,"32,866","97,005","3,050",http://www.governo.gov.ao,...,0.68,0.69,0.21,0.61,-0.12,0.27,-0.23,-0.13,NaN,NaN
5,6,NaN,ATG,28.0,Antigua and Barbuda,HIC,98,"1,618","16,660",http://www.ab.gov.ag,...,0.72,0.55,0.05,0.42,0.00,-0.23,-0.62,-0.59,NaN,NaN

In [93]:
# Must limit the database to the first 206 rows, the remaining rows do not contain any useful information
df = df.iloc[0:205,:]

# Drop the superfluous rows by dropping na
df = df[pd.to_numeric(df['#'], errors='coerce').notnull()]
df['#'] = df[df['#'].notna()]

# Must convert data in the DPL column into float
df['WoG'] = df['WoG'].replace('-',np.nan)
df['WoG'] = df['WoG'].astype(float, errors = 'ignore')

In [94]:
df['WoG'].describe

<bound method NDFrame.describe of 1      0.03
2     -0.03
3     -0.03
4      0.03
5     -0.03
       ...
200    0.03
201   -0.03
202   -0.03
203   -0.03
204   -0.03
Name: WoG, Length: 197, dtype: float64>

In [95]:
subpillars[2]
subpillar = subpillars[2]
print(subpillar)

Leadership and coordination

In [96]:
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['WoG']
df['Country Name'] = df['Economy']
df['Year'] = 2020
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

max_rank

0.09

In [97]:
# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min= -0.03,old_max=0.09))

In [98]:
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
1,Albania,2020,Evidence of focus on vulnerable groups,0.03,3.495,True,Leadership and coordination
2,Algeria,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
3,Andorra,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
4,Angola,2020,Evidence of focus on vulnerable groups,0.03,3.495,True,Leadership and coordination
5,Antigua and Barbuda,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
...,...,...,...,...,...,...,...
200,Vietnam,2020,Evidence of focus on vulnerable groups,0.03,3.495,True,Leadership and coordination
201,Palestine,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
202,Yemen,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
203,Zambia,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination
204,Zimbabwe,2020,Evidence of focus on vulnerable groups,-0.03,1.000,True,Leadership and coordination

## 11. % of digital skills certifications / training courses completed

In [99]:
indicator = indicators[10]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))
df['Average'] = (df['Technology']+df['Data Science'])/2

% of digital skills certifications / training courses completed
digital_skill_level

In [100]:
df

,Global Rank,Region,Country and Region,Year,Technology,Data Science,Average
0,1,Europe,Switzerland,2020,0.84,0.96,0.900
1,2,Europe,Luxembourg,2020,0.62,0.85,0.735
2,3,Europe,Austria,2020,0.88,0.95,0.915
3,4,Asia Pacific,Japan,2020,1.00,0.88,0.940
4,5,Europe,Germany,2020,0.89,0.94,0.915
...,...,...,...,...,...,...,...
103,104,Asia Pacific,Uzbekistan,2020,0.06,0.09,0.075
104,105,Sub-Saharan Africa,Sierra Leone,2020,0.02,0.04,0.030
105,106,Latin America and the Caribbean,Paraguay,2020,0.07,0.11,0.090
106,107,Latin America and the Caribbean,Guyana,2020,0.08,0.02,0.050
107,108,Sub-Saharan Africa,Somalia,2020,0.01,0.01,0.010

In [101]:
subpillars[3]
subpillar = subpillars[3]
print(subpillar)

Capabilities

In [102]:
dcol = 'Global Rank'
indicol = indicator
cname = 'Country and Region'

# filter most recent year
# df = df[(df.TIME==2010)]

# create standard columns
df['higher_is_better'] = True
df['Indicator'] =  indicator
df['Country Name'] = df[cname]
# # df['2019 [YR2019]'] = df['2019 [YR2019]'].astype(float)
df['data_col'] = df['Average']
df['Sub-Pillar'] = subpillar

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=0,old_max=1))


# # prepare output
df = df[['Country Name', 'Year','Indicator','data_col','new_rank_score','higher_is_better','Sub-Pillar']]

# # output scores
df.to_csv('../indicator_scores/government_ percentage digital skills certifications_scores.csv'.format(indicator), index=False)

In [103]:
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar
0,Switzerland,2020,% of digital skills certifications / training ...,0.900,5.49100,True,Capabilities
1,Luxembourg,2020,% of digital skills certifications / training ...,0.735,4.66765,True,Capabilities
2,Austria,2020,% of digital skills certifications / training ...,0.915,5.56585,True,Capabilities
3,Japan,2020,% of digital skills certifications / training ...,0.940,5.69060,True,Capabilities
4,Germany,2020,% of digital skills certifications / training ...,0.915,5.56585,True,Capabilities
...,...,...,...,...,...,...,...
103,Uzbekistan,2020,% of digital skills certifications / training ...,0.075,1.37425,True,Capabilities
104,Sierra Leone,2020,% of digital skills certifications / training ...,0.030,1.14970,True,Capabilities
105,Paraguay,2020,% of digital skills certifications / training ...,0.090,1.44910,True,Capabilities
106,Guyana,2020,% of digital skills certifications / training ...,0.050,1.24950,True,Capabilities
107,Somalia,2020,% of digital skills certifications / training ...,0.010,1.04990,True,Capabilities

### Score Aggregating

In [104]:
import os

In [105]:
# get list of files in scores folder
scores = os.listdir('../indicator_scores/')
scores = [s for s in scores if s.startswith('government')]

In [106]:
scores

['government_ percentage digital skills certifications_scores.csv',
 'government_E-Participation index_scores.csv',
 'government_ICT investment as a percentage of GDP_scores.csv',
 'government_Online-Service-Index (OSI)_scores.csv',
 'government_R&D spending (% of GDP)_scores.csv',
 'government_Security incidents (# of relevant issues)_scores.csv',
 'government_Use of public services online (% of services online, penetration, frequency of use)_scores.csv']

In [107]:
# create a dataframe that concatenates all these file into one table
df = pd.concat([pd.read_csv('../indicator_scores/{}'.format(s)) for s in scores])

In [108]:
df

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar,Unnamed: 0
0,Switzerland,2020.0,% of digital skills certifications / training ...,0.900,5.49100,True,Capabilities,NaN
1,Luxembourg,2020.0,% of digital skills certifications / training ...,0.735,4.66765,True,Capabilities,NaN
2,Austria,2020.0,% of digital skills certifications / training ...,0.915,5.56585,True,Capabilities,NaN
3,Japan,2020.0,% of digital skills certifications / training ...,0.940,5.69060,True,Capabilities,NaN
4,Germany,2020.0,% of digital skills certifications / training ...,0.915,5.56585,True,Capabilities,NaN
...,...,...,...,...,...,...,...,...
30,Germany,2020.0,Use of public services online (% of services o...,62.700,4.12873,True,Digital Public Services,NaN
31,Netherlands,2020.0,Use of public services online (% of services o...,62.700,4.12873,True,Digital Public Services,NaN
32,Morocco,2020.0,Use of public services online (% of services o...,62.300,4.10877,True,Digital Public Services,NaN
33,South Korea,2020.0,Use of public services online (% of services o...,59.700,3.97903,True,Digital Public Services,NaN
34,Japan,2020.0,Use of public services online (% of services o...,45.700,3.28043,True,Digital Public Services,NaN

In [109]:
# Data cleaning
df['new_rank_score'] = df['new_rank_score'].fillna(0)
df.sort_values(by=['Country Name'], ascending=True, inplace=True)
df.reset_index(drop=True, inplace=True)

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country Name      825 non-null    object
 1   Year              825 non-null    float64
 2   Indicator         825 non-null    object
 3   data_col          667 non-null    float64
 4   new_rank_score    825 non-null    float64
 5   higher_is_better  825 non-null    bool
 6   Sub-Pillar        825 non-null    object
 7   Unnamed: 0        386 non-null    float64
dtypes: bool(1), float64(4), object(3)
memory usage: 46.0+ KB

In [111]:
df.head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar,Unnamed: 0
0,Afghanistan,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
1,Afghanistan,2020.0,E-Participation index,0.4643,3.316857,True,Digital Public Services,29.0
2,Afghanistan,2020.0,Online-Service-Index (OSI),0.4118,3.054882,True,Digital Public Services,29.0
3,Africa Eastern and Southern,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
4,Africa Western and Central,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
5,Albania,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
6,Albania,2020.0,Online-Service-Index (OSI),0.8412,5.197588,True,Digital Public Services,36.0
7,Albania,2020.0,E-Participation index,0.8452,5.217548,True,Digital Public Services,36.0
8,Algeria,2020.0,% of digital skills certifications / training ...,0.2600,2.297400,True,Capabilities,NaN
9,Algeria,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
10,Algeria,2020.0,E-Participation index,0.1548,1.772452,True,Digital Public Services,37.0
11,Algeria,2020.0,Online-Service-Index (OSI),0.2765,2.379735,True,Digital Public Services,37.0
12,American Samoa,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
13,Andorra,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
14,Andorra,2020.0,E-Participation index,0.5119,3.554381,True,Digital Public Services,38.0

In [112]:
df.describe()

              Year    data_col  new_rank_score  Unnamed: 0
count   825.000000  667.000000      825.000000  386.000000
mean   2019.233939    4.552073        2.682094   96.000000
std       1.384664   15.774896        1.909363   55.785861
min    2010.000000    0.000000        0.000000    0.000000
25%    2018.000000    0.337584        1.033457   48.000000
50%    2020.000000    0.610000        2.732029   96.000000
75%    2020.000000    0.857797        4.434118  144.000000
max    2020.000000   86.100000        5.990000  192.000000

In [113]:
# checking country names
# sorted(df['Country Name'].unique().tolist())

In [114]:
# remove trailing whitespaces from country name
df['Country Name'] = df['Country Name'].str.strip()
df['Country Name'] = df['Country Name'].str.strip('**')
df['Country Name'] = df['Country Name'].str.strip('*')

In [115]:
df.head()

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar,Unnamed: 0
0,Afghanistan,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
1,Afghanistan,2020.0,E-Participation index,0.4643,3.316857,True,Digital Public Services,29.0
2,Afghanistan,2020.0,Online-Service-Index (OSI),0.4118,3.054882,True,Digital Public Services,29.0
3,Africa Eastern and Southern,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
4,Africa Western and Central,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN

In [116]:
# checking country names
# sorted(df['Country Name'].unique().tolist())

In [117]:
# average indicator scores per country
agg_df = df.groupby(['Country Name']).agg({'new_rank_score':'mean','data_col':'count'})

In [118]:
agg_df.columns = ['agg_score', 'count_source' ]

In [119]:
max_number_sources = agg_df.describe()['count_source']['max']

In [120]:
agg_df['agg_score_wt'] = agg_df['agg_score']*(agg_df['count_source']/max_number_sources)

In [121]:
agg_df.sort_values(by='agg_score', ascending=False, inplace=True)

In [122]:
agg_df.head(25)

,agg_score,count_source,agg_score_wt
Country Name,,,
United Kingdom of Great Britain and Northern Ireland,5.827825,2,1.665093
United States of America,5.414653,3,2.320566
Republic of Korea,5.116750,3,2.192893
Russian Federation (the),4.969820,1,0.709974
Democratic People's Republic of Korea (the),4.863262,1,0.694752
Taiwan,4.842300,1,0.691757
Republic of Moldova,4.779426,2,1.365550
Hong Kong,4.695095,2,1.341456
Viet Nam,4.629170,3,1.983930
Denmark,4.555105,5,3.253646
China,4.509305,6,3.865119
Austria,4.505025,5,3.217875
Singapore,4.452580,4,2.544332
Netherlands,4.372080,5,3.122914
Slovakia,4.359933,3,1.868543
Estonia,4.354422,5,3.110301
Sweden,4.313887,5,3.081348
Russian Federation,4.295181,4,2.454389
Poland,4.280621,5,3.057586
India,4.266098,6,3.656655
Japan,4.254062,6,3.646338
Norway,4.234544,5,3.024675
Bahamas,4.232273,2,1.209221
France,4.227280,6,3.623383
Russia,4.163660,1,0.594809

In [123]:
agg_df.to_csv('../pillar_scores/government_scores_v0.csv')

In [124]:
### Score Aggregating by Subpillars

In [125]:
df.insert(0,'Pillar','Government')
df

,Pillar,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better,Sub-Pillar,Unnamed: 0
0,Government,Afghanistan,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
1,Government,Afghanistan,2020.0,E-Participation index,0.4643,3.316857,True,Digital Public Services,29.0
2,Government,Afghanistan,2020.0,Online-Service-Index (OSI),0.4118,3.054882,True,Digital Public Services,29.0
3,Government,Africa Eastern and Southern,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
4,Government,Africa Western and Central,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
...,...,...,...,...,...,...,...,...,...
820,Government,Zambia,2020.0,E-Participation index,0.3095,2.544405,True,Digital Public Services,177.0
821,Government,Zambia,2020.0,Online-Service-Index (OSI),0.2588,2.291412,True,Digital Public Services,177.0
822,Government,Zimbabwe,2018.0,R&D spending (% of GDP),NaN,0.000000,True,Funding and procurement,NaN
823,Government,Zimbabwe,2020.0,Online-Service-Index (OSI),0.5235,3.612265,True,Digital Public Services,178.0
824,Government,Zimbabwe,2020.0,E-Participation index,0.4524,3.257476,True,Digital Public Services,178.0

In [126]:
sub_df = df.groupby(['Pillar','Sub-Pillar','Country Name']).agg({'new_rank_score':'mean','data_col':'count'})

In [127]:
sub_df.columns = ['agg_score', 'count_source' ]

In [128]:
max_number_sources = sub_df.describe()['count_source']['max']

In [129]:
sub_df['agg_score_wt'] = sub_df['agg_score']*(sub_df['count_source']/max_number_sources)

In [130]:
sub_df.to_csv('../subpillar_score/government_scores_subpillar_v0.csv')

### Sources Generation

In [131]:
#Get all countries from Countries.xlsx
countries = pd.read_excel('../../data/Countries.xlsx')
col_names = ['Country or Area']
countries = countries[col_names]
countries.rename(columns = {'Country or Area': 'Country Name'}, inplace = True)

In [132]:
#Get all indicators from names dataframe retrieve at the begining of the script
bnames=bnames[['check','Sub-Pillar','Indicator','Data Source','Data Link']]
bnames.rename(columns = {'check': 'Pillar'}, inplace = True)
bnames = bnames.replace('\n','', regex=True)

In [133]:
#Do a nice cross join so that we have combination of all countries vs all indicators
sources = countries.merge(bnames, how='cross')
sources

,Country Name,Pillar,Sub-Pillar,Indicator,Data Source,Data Link
0,Algeria,Government,Digital Public Services,Online-Service-Index (OSI),UN: E-Government Survey,https://publicadministration.un.org/egovkb
1,Algeria,Government,Digital Public Services,E-Participation index,UN: E-Government Survey,https://publicadministration.un.org/egovkb
2,Algeria,Government,Digital Public Services,Use of public services online (% of services o...,Boston Consulting Group/Salesforce: The Global...,https://www.salesforce.com
3,Algeria,Government,Digital Public Services,Security incidents (# of relevant issues),SPECOPS,https://specopssoft.com
4,Algeria,Government,Digital Public Services,Inherent Cyber Risk,FM Global: FM Global Resilience Index,https://www.fmglobal.com/
...,...,...,...,...,...,...
2734,Wallis and Futuna Islands,Government,Funding and procurement,R&D spending (% of GDP),World Bank: World Development Indicators,https://datacatalog.worldbank.org
2735,Wallis and Futuna Islands,Government,Funding and procurement,ICT investment as a percentage of GDP,OECD: Going Digital Toolkit,https://data.oecd.org
2736,Wallis and Futuna Islands,Government,Funding and procurement,Evidence of digital strategies in/across Minis...,World Bank: GovTech Dataset,https://datacatalog.worldbank.org
2737,Wallis and Futuna Islands,Government,Leadership and coordination,Evidence of focus on vulnerable groups,World Bank: GovTech Dataset,https://datacatalog.worldbank.org
2738,Wallis and Futuna Islands,Government,Capabilities,% of digital skills certifications / training ...,Coursera: Global Skills Reports,https://www.coursera.org/skills-reports/global

In [134]:
#Make copy of a scores dataframe and add the column available, with value of 1 (string)
#denoting all the country/indicator combinations that have value
dfsources = df[['Country Name','Pillar','Sub-Pillar','Indicator']].copy()
dfsources['Available'] = '1'

In [135]:
#If sources.csv exists, get the contents, remove everyhing from this pillar, append prepared sources, save csv.
#if sources.csv does not exist, create new file from sources.
from os.path import exists

if exists('../../dashboard/Sources.csv') :
    CurrentSources = pd.read_csv('../../dashboard/Sources.csv', dtype=str)
    CurrentSources = CurrentSources[['Country Name','Pillar','Sub-Pillar','Indicator','Data Source','Data Link','Available']]
    CurrentSources = CurrentSources.loc[CurrentSources['Pillar'] != 'Government']
    CurrentSources = CurrentSources.append(sources)
else :
    CurrentSources = sources
CurrentSources

,Country Name,Pillar,Sub-Pillar,Indicator,Data Source,Data Link,Available
0,Algeria,Foundations,Digital Payments,Digital payments penetration,Portulans Institute: Network Readiness Index,https://networkreadinessindex.org,0
1,Algeria,Foundations,Digital Payments,% of population with digital finance account,World Bank: Global Findex database,https://datacatalog.worldbank.org,1
2,Algeria,Foundations,Digital Payments,Made or received digital payments in the past ...,World Bank: Global Findex database,https://datacatalog.worldbank.org,1
3,Algeria,Foundations,Digital Payments,Made or received digital payments in the past ...,World Bank: Global Findex database,https://datacatalog.worldbank.org,1
4,Algeria,Foundations,Digital Payments,Used a mobile phone or the internet to check a...,World Bank: Global Findex database,https://datacatalog.worldbank.org,1
...,...,...,...,...,...,...,...
2734,Wallis and Futuna Islands,Government,Funding and procurement,R&D spending (% of GDP),World Bank: World Development Indicators,https://datacatalog.worldbank.org,NaN
2735,Wallis and Futuna Islands,Government,Funding and procurement,ICT investment as a percentage of GDP,OECD: Going Digital Toolkit,https://data.oecd.org,NaN
2736,Wallis and Futuna Islands,Government,Funding and procurement,Evidence of digital strategies in/across Minis...,World Bank: GovTech Dataset,https://datacatalog.worldbank.org,NaN
2737,Wallis and Futuna Islands,Government,Leadership and coordination,Evidence of focus on vulnerable groups,World Bank: GovTech Dataset,https://datacatalog.worldbank.org,NaN
2738,Wallis and Futuna Islands,Government,Capabilities,% of digital skills certifications / training ...,Coursera: Global Skills Reports,https://www.coursera.org/skills-reports/global,NaN

In [136]:
CurrentSources.to_csv('../../dashboard/Sources.csv', index=False)