In [1]:
import pandas as pd
import numpy as np

In [2]:
### Get all the pillar names from the excel

In [3]:
names = pd.read_excel('../../UNDP Digital Assessment Data Framework Filename Matching V7.xlsx')

In [4]:
col_names = ['Indicator','check', 'Data Source','Index','Filename']

In [5]:
names = names[col_names]

In [6]:
names.head()

,Indicator,check,Data Source,Index,Filename
0,Countries,NaN,United Nations,False,Countries
1,"Database of Global Administrative Areas (GADM,...",NaN,GADM maps and data,False,NaN
2,High Resolution Population Density Maps + Demo...,NaN,Facebook,False,NaN
3,population density vs openstreetmap object den...,NaN,Kontur,False,NaN
4,Population Density,Infrastructure,World Bank,False,population_density

In [7]:
# get all the files per pillar
data_stats = names.groupby('check').agg({'Filename':'count','Indicator':'count'})

In [8]:
data_stats

                Filename  Indicator
check
Business              20         25
Foundations            7         12
Government            10         15
Infrastructure        38         48
People                35         47
Regulation             6          7
Strategy               1          1

In [9]:
### Infrastructure

In [10]:
bnames = names[(names.check=='Infrastructure')&(~names.Filename.isna())]#&(names.Index==False)]
bnames.head(25)

,Indicator,check,Data Source,Index,Filename
4,Population Density,Infrastructure,World Bank,False,population_density
6,% of population covered by internet connectivity,Infrastructure,ITU,False,ITU_database
7,% of population covered by mobile 2G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
8,% of population covered by mobile 3G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
9,% of population covered by mobile 4G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
10,% of population covered by mobile 5G+ data con...,Infrastructure,GSMA Mobile Connectivity Index,False,countries_mobile_connectivity
11,Mobile Coverage Maps,Infrastructure,ITU,False,ITU_database
12,Electricity Density,Infrastructure,Energy Data,False,electricity_yearbook
13,% of population covered by electricity,Infrastructure,World Bank,False,population_electricity_coverage
14,Electricity supply quality,Infrastructure,International Energy Agency / Global Competiti...,False,elect_supply_quality
15,Electricity Environmental Sustainability,Infrastructure,The Sustainable Development Report/ Cambridge ...,False,sustainability_index
17,Cellphone Signal Density,Infrastructure,GSMA Mobile Connectivity Index,False,mobile_density
18,Telecommunication Infrastructure Index (TII),Infrastructure,DESA,True,e_government_index
19,GSMA Mobile Connectivity Index,Infrastructure,GSMA Mobile Connectivity Index,True,countries_mobile_connectivity
20,Spectrum Allocated to Mobile Providers,Infrastructure,GSMA Mobile Connectivity Index,False,spectrum_allocated_mobile_providers
23,Internet Exchange Points (IXPs) map,Infrastructure,Packet Clearing House,False,countries_ixp
26,ISP internet download speed average,Infrastructure,Ookla's Speedtest Intelligence,False,internet_speed
28,Mobile dowload speed at the slowest hour of th...,Infrastructure,GSMA Mobile Connectivity Index,False,mobile_latency
29,Mobile download speed average,Infrastructure,Ookla's Speedtest Intelligence,False,mobile_speed
30,Individuals using the Internet (% of population),Infrastructure,ITU,False,ITU_database
31,Mobile cellular subscriptions (per 100 people),Infrastructure,ITU,False,ITU_database
32,Average fixed broadband download speeds,Infrastructure,Ookla's Speedtest Intelligence,False,fixed_bdbd_spd_dl_ul
35,Postal Coverage,Infrastructure,Universal Postal Union,False,postal_coverage
36,Logistics Performance Index (LPI) - Infrastruc...,Infrastructure,World Bank,True,logistics_performance_index
38,National cyber security index,Infrastructure,e-Governance Academy Foundation,True,national_cybersecurity_index

In [11]:
# get list of names for all indicators
indicators = bnames.Indicator.unique()

In [12]:
# get all file names
bfiles = bnames.Filename.unique()

In [13]:
bfiles

array(['population_density', 'ITU_database',
       'countries_mobile_connectivity', 'electricity_yearbook',
       'population_electricity_coverage', 'elect_supply_quality',
       'sustainability_index', 'mobile_density', 'e_government_index',
       'spectrum_allocated_mobile_providers', 'countries_ixp',
       'internet_speed', 'mobile_latency', 'mobile_speed',
       'fixed_bdbd_spd_dl_ul', 'postal_coverage',
       'logistics_performance_index', 'national_cybersecurity_index',
       'dice_export_global_cybersecurity_index',
       'software_developer_ecosystem_size',
       'digital_platform_economy_index', 'migration_skill',
       'migration_industry', 'migration_country',
       'global_fintech_ranking', 'tech_hubs', 'banking_sector_size',
       'angel_investment', 'startup_eco_size',
       'international_co_inventions'], dtype=object)

In [14]:
# formula for converting scale
def convert_rank(old_value, old_min=1, old_max=7, new_min=1, new_max=6 ):
    """ Convert old scale values scale into new scale values"""
    old_range = old_max - old_min
    new_range = new_max - new_min
    new_value = (((old_value-old_min)*new_range)/old_range)+new_min
    return new_value

In [15]:
### 2. % of population covered by internet connectivity

In [16]:
indicators[1]

# load data
indicator = indicators[1]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by internet connectivity
ITU_database

In [17]:
df = df[(df.Year == 2020)]
df = df[(df['Indicator name']== 'Individuals using the Internet, total (%)')]
df

,Country,Region,ISO,Indicator name,Year,Value,data_country,data_year
47744,Mauritius,Africa,MUS,"Individuals using the Internet, total (%)",2020.0,64.884904,NaN,NaN
47745,Uganda,Africa,UGA,"Individuals using the Internet, total (%)",2020.0,NaN,NaN,NaN
47746,Bahrain,Arab States,BHR,"Individuals using the Internet, total (%)",2020.0,99.539512,NaN,NaN
47747,Egypt,Arab States,EGY,"Individuals using the Internet, total (%)",2020.0,71.914200,NaN,NaN
47748,Iraq,Arab States,IRQ,"Individuals using the Internet, total (%)",2020.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
47805,Bolivia (Plurinational State of),The Americas,BOL,"Individuals using the Internet, total (%)",2020.0,55.139051,NaN,NaN
47806,Costa Rica,The Americas,CRI,"Individuals using the Internet, total (%)",2020.0,80.530186,NaN,NaN
47807,Mexico,The Americas,MEX,"Individuals using the Internet, total (%)",2020.0,71.970000,NaN,NaN
47808,Paraguay,The Americas,PRY,"Individuals using the Internet, total (%)",2020.0,74.515240,NaN,NaN
47809,Peru,The Americas,PER,"Individuals using the Internet, total (%)",2020.0,65.251799,NaN,NaN

In [18]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Value']
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [19]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better
47744,Mauritius,2020.0,% of population covered by internet connectivity,64.884904,3.298839,True
47745,Uganda,2020.0,% of population covered by internet connectivity,NaN,NaN,True
47746,Bahrain,2020.0,% of population covered by internet connectivity,99.539512,5.964578,True
47747,Egypt,2020.0,% of population covered by internet connectivity,71.914200,3.839554,True
47748,Iraq,2020.0,% of population covered by internet connectivity,NaN,NaN,True
47749,Kuwait,2020.0,% of population covered by internet connectivity,98.599995,5.892307,True
47750,Morocco,2020.0,% of population covered by internet connectivity,84.120363,4.778489,True
47751,Oman,2020.0,% of population covered by internet connectivity,95.232293,5.633253,True
47752,Qatar,2020.0,% of population covered by internet connectivity,99.652794,5.973292,True
47753,Saudi Arabia,2020.0,% of population covered by internet connectivity,97.862332,5.835564,True
47754,United Arab Emirates,2020.0,% of population covered by internet connectivity,100.000000,6.000000,True
47755,Cambodia,2020.0,% of population covered by internet connectivity,78.800000,4.369231,True
47756,China,2020.0,% of population covered by internet connectivity,70.642143,3.741703,True
47757,"Hong Kong, China",2020.0,% of population covered by internet connectivity,92.413136,5.416395,True
47758,Indonesia,2020.0,% of population covered by internet connectivity,53.726494,2.440500,True

In [20]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [21]:
### 3. % of population covered by mobile 2G

In [22]:
indicators[2]

'% of population covered by mobile 2G+ data connectivity'

In [23]:
# load data
indicator = indicators[2]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 2G+ data connectivity
countries_mobile_connectivity

In [24]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [25]:
# filter most recent year
df = df[(df.Year==2019)]

In [26]:
# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [27]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 2G+ data con...,90.00,4.921251,True
11,Angola,2019,% of population covered by mobile 2G+ data con...,90.00,4.921251,True
17,Albania,2019,% of population covered by mobile 2G+ data con...,99.86,5.984898,True
23,United Arab Emirates,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
29,Argentina,2019,% of population covered by mobile 2G+ data con...,98.00,5.784250,True
35,Armenia,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
41,Australia,2019,% of population covered by mobile 2G+ data con...,99.40,5.935275,True
47,Austria,2019,% of population covered by mobile 2G+ data con...,99.00,5.892125,True
53,Azerbaijan,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
59,Burundi,2019,% of population covered by mobile 2G+ data con...,53.65,1.000000,True
65,Belgium,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True
71,Benin,2019,% of population covered by mobile 2G+ data con...,98.00,5.784250,True
77,Burkina Faso,2019,% of population covered by mobile 2G+ data con...,97.90,5.773463,True
83,Bangladesh,2019,% of population covered by mobile 2G+ data con...,99.60,5.956850,True
89,Bulgaria,2019,% of population covered by mobile 2G+ data con...,100.00,6.000000,True

In [28]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [29]:
### 4. % of population covered by mobile 3G

In [30]:
indicators[3]

# load data
indicator = indicators[3]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 4G+ data connectivity
countries_mobile_connectivity

In [31]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [32]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['3G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [33]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 4G+ data con...,58.7,3.282895,True
11,Angola,2019,% of population covered by mobile 4G+ data con...,71.0,4.092105,True
17,Albania,2019,% of population covered by mobile 4G+ data con...,97.0,5.802632,True
23,United Arab Emirates,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True
29,Argentina,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
35,Armenia,2019,% of population covered by mobile 4G+ data con...,99.0,5.934211,True
41,Australia,2019,% of population covered by mobile 4G+ data con...,99.5,5.967105,True
47,Austria,2019,% of population covered by mobile 4G+ data con...,99.0,5.934211,True
53,Azerbaijan,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
59,Burundi,2019,% of population covered by mobile 4G+ data con...,40.0,2.052632,True
65,Belgium,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True
71,Benin,2019,% of population covered by mobile 4G+ data con...,89.0,5.276316,True
77,Burkina Faso,2019,% of population covered by mobile 4G+ data con...,65.0,3.697368,True
83,Bangladesh,2019,% of population covered by mobile 4G+ data con...,95.0,5.671053,True
89,Bulgaria,2019,% of population covered by mobile 4G+ data con...,100.0,6.000000,True

In [34]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [35]:
### 5. % of population covered by mobile 4G

In [36]:
indicators[4]

# load data
indicator = indicators[4]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

% of population covered by mobile 5G+ data connectivity
countries_mobile_connectivity

In [37]:
df.head(10)

,ISO Code,Country,Region,Year,Cluster,Index,Infrastructure,Affordability,Consumer Readiness,Content and Services,...,Gender gap in mobile ownership,TLDs per capita,E-Government Score,Mobile Social Media Penetration,Apps developed per person,Number of apps in national language,Accessibility of top ranked apps,Cybersecurity Index,data_country,data_year
0,AFG,Afghanistan,South Asia,2014,Discoverer,22.12,21.74,31.79,24.40,14.19,...,0.00,39.55,18.11,3.28,20.98,2.44,4.37,26.50,NaN,NaN
1,AFG,Afghanistan,South Asia,2015,Discoverer,22.99,22.82,30.81,25.28,15.71,...,0.00,39.57,24.27,4.36,22.93,2.79,8.03,25.83,NaN,NaN
2,AFG,Afghanistan,South Asia,2016,Discoverer,23.71,26.92,26.75,26.07,16.83,...,0.00,39.58,30.43,6.73,30.31,2.85,5.90,25.17,NaN,NaN
3,AFG,Afghanistan,South Asia,2017,Discoverer,25.82,33.54,27.22,28.56,17.04,...,0.00,39.47,30.50,7.78,31.62,2.91,6.15,24.50,NaN,NaN
4,AFG,Afghanistan,South Asia,2018,Discoverer,28.39,30.91,42.64,29.24,16.87,...,0.00,39.39,30.56,8.54,36.54,2.96,8.66,17.70,NaN,NaN
5,AFG,Afghanistan,South Asia,2019,Discoverer,28.94,32.34,41.53,29.72,17.58,...,0.00,39.41,41.18,9.39,39.36,3.00,5.72,17.70,NaN,NaN
6,AGO,Angola,Sub-Saharan Africa,2014,Discoverer,32.78,25.99,35.99,44.33,27.85,...,51.65,0.00,29.92,3.99,22.74,53.33,49.09,8.80,NaN,NaN
7,AGO,Angola,Sub-Saharan Africa,2015,Emerging,37.18,33.09,42.01,45.41,30.27,...,57.00,0.31,32.35,5.26,22.12,55.08,58.33,8.47,NaN,NaN
8,AGO,Angola,Sub-Saharan Africa,2016,Emerging,39.85,37.80,44.74,46.47,32.11,...,63.73,0.00,34.78,6.27,27.46,56.52,61.73,8.13,NaN,NaN
9,AGO,Angola,Sub-Saharan Africa,2017,Emerging,42.89,48.60,47.94,46.32,31.36,...,53.97,0.00,37.88,4.26,31.94,57.06,55.09,7.80,NaN,NaN

In [38]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['4G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [39]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

,Country Name,Year,Indicator,data_col,new_rank_score,higher_is_better
5,Afghanistan,2019,% of population covered by mobile 5G+ data con...,15.00,1.7500,True
11,Angola,2019,% of population covered by mobile 5G+ data con...,50.00,3.5000,True
17,Albania,2019,% of population covered by mobile 5G+ data con...,96.00,5.8000,True
23,United Arab Emirates,2019,% of population covered by mobile 5G+ data con...,99.00,5.9500,True
29,Argentina,2019,% of population covered by mobile 5G+ data con...,89.77,5.4885,True
35,Armenia,2019,% of population covered by mobile 5G+ data con...,95.00,5.7500,True
41,Australia,2019,% of population covered by mobile 5G+ data con...,99.20,5.9600,True
47,Austria,2019,% of population covered by mobile 5G+ data con...,99.00,5.9500,True
53,Azerbaijan,2019,% of population covered by mobile 5G+ data con...,90.00,5.5000,True
59,Burundi,2019,% of population covered by mobile 5G+ data con...,25.00,2.2500,True
65,Belgium,2019,% of population covered by mobile 5G+ data con...,100.00,6.0000,True
71,Benin,2019,% of population covered by mobile 5G+ data con...,45.00,3.2500,True
77,Burkina Faso,2019,% of population covered by mobile 5G+ data con...,8.64,1.4320,True
83,Bangladesh,2019,% of population covered by mobile 5G+ data con...,80.00,5.0000,True
89,Bulgaria,2019,% of population covered by mobile 5G+ data con...,100.00,6.0000,True

In [40]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [41]:
### 6. % of population covered by mobile 5G

In [42]:
indicators[5]

# load data
indicator = indicators[5]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

Mobile Coverage Maps
ITU_database

In [43]:
df.head(10)

,Country,Region,ISO,Indicator name,Year,Value,data_country,data_year
0,Angola,Africa,AGO,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
1,Benin,Africa,BEN,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
2,Botswana,Africa,BWA,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
3,Burkina Faso,Africa,BFA,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
4,Burundi,Africa,BDI,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
5,Cabo Verde,Africa,CPV,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
6,Cameroon,Africa,CMR,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
7,Central African Rep.,Africa,CAF,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
8,Chad,Africa,TCD,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN
9,Congo (Rep. of the),Africa,COG,Female mobile phone ownership as a % of total ...,2010.0,NaN,NaN,NaN

In [44]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['5G Coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

KeyError: '5G Coverage'

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 7. Mobile Coverage Maps

In [ ]:
indicators[6]

# load data
indicator = indicators[6]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df = df[(df.Year == 2020)]
df = df[(df['Indicator name']== 'Mobile-cellular subscriptions per 100 inhabitants')]
df

In [ ]:
# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Value'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 8. Electricity Density

In [ ]:
indicators[7]

# load data
indicator = indicators[7]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(20)

In [ ]:
# create standard columns
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2017'] 
df['Country Name'] = df['Unnamed: 28']
df['Year'] = 2017

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 10. % of population covered by electricity

In [ ]:
indicators[9]

# load data
indicator = indicators[9]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2019'] 
df['Year'] = 2019

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 11. Electricity Supply Quality

In [ ]:
indicators[10]

# load data
indicator = indicators[10]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(10)

In [ ]:
# The data needs to be transposed as countries are now in columns, not rows, which could present problems for later.

In [ ]:
### 12. Electricity Environmental Sustainability

In [ ]:
indicators[11]

# load data
indicator = indicators[11]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['2021 SDG Index Score'] 
df['Year'] = 2021

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 13. Cellphone Signal Density

In [ ]:
indicators[12]

# load data
indicator = indicators[12]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(10)

In [ ]:
df = df[(df.Year == 2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Network coverage'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 14. Telecommunication Infrastructure Index (TII)

In [ ]:
indicators[13]

# load data
indicator = indicators[13]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(10)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Telecommunication Infrastructure Index'] 
df['Year'] = df['Survey Year']

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 15. GSMA Mobile Connectivity Index

In [ ]:
indicators[14]

# load data
indicator = indicators[14]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(10)

In [ ]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Index'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 16. Spectrum Allocated to Mobile Providers

In [ ]:
indicators[15]

# load data
indicator = indicators[15]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
df.rename(columns={'Country':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Spectrum'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 17. Internet Exchange Points (IXPs)

In [ ]:
indicators[16]

# load data
indicator = indicators[16]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df['Country Name'] = df['Country']
df.head(15)

In [ ]:
agg_df = df.groupby('Country Name').agg({'Country':'count'})
agg_df

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

agg_df['higher_is_better'] = True
agg_df['Indicator'] = indicator
agg_df['data_col'] = agg_df['Country'] 
agg_df['Year'] = 2019

min_rank = agg_df['data_col'].min()
max_rank = agg_df['data_col'].max()

# transform 0-1 rank into 1-6
agg_df['new_rank_score'] = agg_df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
agg_df[['Year','Indicator','data_col','new_rank_score','higher_is_better']].head(150)

In [ ]:
agg_df[['Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 18. ISP internet download speed averag

In [ ]:
indicators[17]

# load data
indicator = indicators[17]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Download speed (Mbps)'] 
df['Country Name'] = df['Country']

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 19. Mobile dowload speed at the slowest hour

In [ ]:
indicators[18]

# load data
indicator = indicators[18]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

# Waiting for internet_speed to be added to the processed folder

In [ ]:
df.head(15)

In [ ]:
# filter most recent year
df = df[(df.Year==2019)]

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Mobile latencies'] 
df['Country Name'] = df['Country']

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))


# invert since to lower rank is better
df['new_rank_score'] = df['new_rank_score'].apply(lambda row: (6-row)+1)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 20. Mobile download speed average

In [ ]:
indicators[19]

# load data
indicator = indicators[19]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Mbps'] 
df['Country Name'] = df['Country']

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 21. Individuals using the Internet (% of population)

In [ ]:
indicators[20]

# load data
indicator = indicators[20]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df = df[(df['Indicator name'] == 'Individuals using the Internet, total (%)')]
df = df[(df.Year==2019)]
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Value'] 
df.rename(columns = {'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(150)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 22. Mobile-cellular subscriptions per 100 inhabitants

In [ ]:
indicators[21]

# load data
indicator = indicators[21]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df = df[(df['Indicator name'] == 'Individuals using the Internet, total (%)')]
df = df[(df.Year==2020)]
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Indicator'] = indicator
df['data_col'] = df['Value'] 
df.rename(columns = {'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(150)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 23. Average fixed broadband download speeds

In [ ]:
indicators[22]

# load data
indicator = indicators[22]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns

df.rename(columns={'Country':'Country Name'}, inplace=True)
df['higher_is_better'] = True
df['Year'] = 2021
df['Indicator'] = indicator
df['data_col'] = df['broadband'] 
df.rename(columns = {'country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 24. Postal Coverage

In [ ]:
indicators[23]

# load data
indicator = indicators[23]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
#Choose 'Percent of Population Having Mail Delivered at Home' as the data column
df = df[(df.Indicator=='Percent of Population Having Mail Delivered at Home')]
df.head(15)

# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2015
df['Indicator'] = indicator
df['data_col'] = df['2015'] 

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 25. Logistics Performance Index (LPI)

In [ ]:
indicators[24]

# load data
indicator = indicators[24]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2018
df['Indicator'] = indicator
df['data_col'] = df['score']
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 26. National cyber security index

In [ ]:
indicators[25]

# load data
indicator = indicators[25]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2021
df['Indicator'] = indicator
df['data_col'] = df['National Cyber Security Index']
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 27. Global Cybersecurity Index (GCI)

In [ ]:
indicators[26]

# load data
indicator = indicators[26]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2020
df['Indicator'] = indicator
df['data_col'] = df['Score (2020)'] 
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 28. Software Developer Ecosystem size

In [ ]:
indicators[27]

# load data
indicator = indicators[27]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df['higher_is_better'] = True
df['Year'] = 2018
df['Indicator'] = indicator
df['data_col'] = df.iloc[:,[1]]
df.rename(columns={'Country':'Country Name'}, inplace=True)
    
min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 29. Digital Work Ecosystem size

In [ ]:
indicators[28]

# load data
indicator = indicators[28]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = False
df['Year'] = 2020
df['Indicator'] = indicator
df['data_col'] = df.iloc[:,[0]].astype(float)
df.rename(columns={'Country':'Country Name'}, inplace=True)
    
min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

# invert since to lower rank is better
df['new_rank_score'] = df['new_rank_score'].apply(lambda row: (6-row)+1)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 30. Country, Industry, Skill Migration Data (Skill)

In [ ]:
indicators[29]

# load data
indicator = indicators[29]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df['Country Name'] = df.iloc[:,[1]]

df_sum = df.groupby('Country Name')[['net_per_10K_2019']].sum()
df_sum

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df_sum['higher_is_better'] = True
df_sum['Year'] = 2019
df_sum['Indicator'] = indicator
df_sum['data_col'] = df_sum['net_per_10K_2019']


min_rank = df_sum['data_col'].min()
max_rank = df_sum['data_col'].max()

# transform 0-1 rank into 1-6
df_sum['new_rank_score'] = df_sum['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 31. Country, Industry, Skill Migration Data (Industry)

In [ ]:
indicators[30]

# load data
indicator = indicators[30]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df['Country Name'] = df.iloc[:,[1]]

df_sum = df.groupby('Country Name')[['net_per_10K_2019']].sum()
df_sum

In [ ]:
## create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df_sum['higher_is_better'] = True
df_sum['Year'] = 2019
df_sum['Indicator'] = indicator
df_sum['data_col'] = df_sum['net_per_10K_2019']


min_rank = df_sum['data_col'].min()
max_rank = df_sum['data_col'].max()

# transform 0-1 rank into 1-6
df_sum['new_rank_score'] = df_sum['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 32. Country, Industry, Skill Migration Data (Nation)

In [ ]:
indicators[31]

# load data
indicator = indicators[31]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
df['Country Name'] = df.iloc[:,[1]]

df_sum = df.groupby('Country Name')[['net_per_10K_2019']].sum()
df_sum

In [ ]:
## create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df_sum['higher_is_better'] = True
df_sum['Year'] = 2019
df_sum['Indicator'] = indicator
df_sum['data_col'] = df_sum['net_per_10K_2019']


min_rank = df_sum['data_col'].min()
max_rank = df_sum['data_col'].max()

# transform 0-1 rank into 1-6
df_sum['new_rank_score'] = df_sum['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 33. Digital Finance Ecosystem size

In [ ]:
indicators[32]

# load data
indicator = indicators[32]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2021
df['Indicator'] = indicator
df['data_col'] = df.iloc[:,[2]]
df['Country Name'] = df.iloc[:,[1]]

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

# Have to shorten the column names to see if this works

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 34. Tech hubs & spaces size

In [ ]:
indicators[33]

# load data
indicator = indicators[33]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

#There are two problems:
#1. The column names need some overhaul (moving the second column to the top and make it the column names)
#2. This is a list of cities, not countries, may present probkems later.

In [ ]:
### 35. Banking Ecosystem size

In [ ]:
indicators[34]

# load data
indicator = indicators[34]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2017
df['Indicator'] = indicator
df['data_col'] = df['Bank assets, percent of GDP, 2017']
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))# Okay but will have to remove number from the Country column, leaving only characters.

In [ ]:

df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 36. Angel Ecosystem size

In [ ]:
indicators[35]

# load data
indicator = indicators[35]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df['higher_is_better'] = True
df['Year'] = 2019
df['Indicator'] = indicator
df['data_col'] = df['Business angel investments (in million Euros)']
df.rename(columns={'Country':'Country Name'}, inplace=True)

min_rank = df['data_col'].min()
max_rank = df['data_col'].max()

# transform 0-1 rank into 1-6
df['new_rank_score'] = df['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

# Okay but there are only EU countries

In [ ]:
df[['Country Name','Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### 37. Startup Ecosystem size

In [ ]:
indicators[36]

# load data
indicator = indicators[36]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

# This is a list of cities, not countries, wonder if it will work

In [ ]:
### 38. Venture Ecosystem size

indicators[37]

# load data
indicator = indicators[37]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

# Similar to the previous one

In [ ]:
### 39. International Co-Inventions

In [ ]:
indicators[38]

# load data
indicator = indicators[38]
print(indicator)
bf = bnames[bnames['Indicator']==indicator]['Filename'].values[0]
print(bf)

df = pd.read_csv('../../processed/{}.csv'.format(bf))

In [ ]:
df.head(15)

In [ ]:
# filter most recent year and global value
df = df[(df.Time==2017)]
df = df[(df.Country!='World')]
df ['Country Name'] = df ['Country']
df

In [ ]:
# Create summarization
df_sum = df.groupby('Country Name')[['Value']].sum()
df_sum

In [ ]:
# create standard columns
# df.rename(columns={'COUNTRY/ECONOMY':'Country Name'}, inplace=True)

df_sum['higher_is_better'] = True
df_sum['Year'] = 2017
df_sum['Indicator'] = indicator
df_sum['data_col'] = df_sum.iloc[:,[0]]

min_rank = df_sum['data_col'].min()
max_rank = df_sum['data_col'].max()

# transform 0-1 rank into 1-6
df_sum['new_rank_score'] = df_sum['data_col'].apply(lambda row: convert_rank(row,old_min=min_rank,old_max=max_rank))

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].head(15)

# Okay but the data is too general with many missing countries

In [ ]:
df_sum[['Year','Indicator','data_col','new_rank_score','higher_is_better']].to_csv('../indicator_scores/infrastructure_{}_scores.csv'.format(indicator, index=False))

In [ ]:
### Score Aggregating

In [ ]:
import os

In [ ]:
# get list of files in scores folder
scores = os.listdir('../indicator_scores/')
scores = [s for s in scores if s.startswith('infrastructure')]

In [ ]:
scores

In [ ]:
# create a dataframe that concatenates all these file into one table
df = pd.concat([pd.read_csv('../indicator_scores/{}'.format(s)) for s in scores])

In [ ]:
df

In [ ]:
# Data cleaning
df['new_rank_score'] = df['new_rank_score'].fillna(0)
df.sort_values(by=['Country Name'], ascending=True, inplace=True)
df.reset_index(drop=True, inplace=True)

# remove trailing whitespaces from country name
df['Country Name'] = df['Country Name'].str.strip()
df['Country Name'] = df['Country Name'].str.strip('**')
df['Country Name'] = df['Country Name'].str.strip('*')


# Replace values that are not truly country names with nan
df['Country Name'] = df['Country Name'].replace('n.a. : non avalaible',np.nan)
df['Country Name'] = df['Country Name'].replace('nan',np.nan)
df['Country Name'] = df['Country Name'].replace('Not classified',np.nan)
df['Country Name'] = df['Country Name'].replace('Source :',np.nan)
df['Country Name'] = df['Country Name'].replace('© Copyright Enerdata. Reproduction and diffusion prohibited (web, photocopy, intranet...) without written permission.',np.nan)

# Dropping the columns having NaN/NaT values
df = df[df['Country Name'].notna()]


df['Country Name'] = df['Country Name'].astype(str, errors = 'ignore')

In [ ]:
df.info()

In [ ]:
df.head(15)

In [ ]:
sorted(df['Country Name'].unique().tolist())

In [ ]:
df.head(15)

In [ ]:
# average indicator scores per country
agg_df = df.groupby(['Country Name']).agg({'new_rank_score':'mean','data_col':'count'})

In [ ]:
agg_df.columns = ['agg_score', 'count_source' ]

In [ ]:
max_number_sources = agg_df.describe()['count_source']['max']

In [ ]:
agg_df['agg_score_wt'] = agg_df['agg_score']*(agg_df['count_source']/max_number_sources)

In [ ]:
agg_df.sort_values(by='agg_score', ascending=False, inplace=True)

In [ ]:
agg_df.head(25)

In [ ]:
agg_df.to_csv('../pillar_scores/infrastructure_scores_v0.csv')