In [1]:
import pandas as pd
import numpy as np
import os 
import re

In [2]:
### Score Aggregating by Subpillars

In [3]:
# get list of files in scores folder
scores = os.listdir('../../score/HR_scores_agg/')
scores

df = pd.concat([pd.read_csv('../../score/HR_scores_agg/{}'.format(s)) for s in scores])

In [4]:
#Drop all the 0 value in source
df = df[df['count_source'] != 0]

In [5]:
df['Country Name'] = df['Country Name'].str.strip()
df['Country Name'] = df['Country Name'].str.strip('**')
df['Country Name'] = df['Country Name'].str.strip('*')
df['Country Name'] = df['Country Name'].str.strip('*')
df['Country Name'] = df['Country Name'].replace('-',np.nan)
df['Country Name'] = df['Country Name'].replace('0.03',np.nan)
df = df.dropna()

In [6]:
# Normalize country names as much as possible

df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
df['Country Name'] = df['Country Name'].replace('Bahrain (Kingdom of)','Bahrain')
df['Country Name'] = df['Country Name'].replace('Bolivia','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Bolivia, Plurinational State of','Bolivia (Plurinational State of)')
df['Country Name'] = df['Country Name'].replace('Brunei','Brunei Darussalam')
df['Country Name'] = df['Country Name'].replace('Bulgaria (Rep.)','Bulgaria')
df['Country Name'] = df['Country Name'].replace('Central African Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Central African Rep.','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace("China (People's Rep.)",'China')
df['Country Name'] = df['Country Name'].replace("Comoros",'Comoros (the)')
df['Country Name'] = df['Country Name'].replace("Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Brazzaville)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Rep. of the)",'Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo (Democratic Republic of the)",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, Dem. Rep.",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Congo, The Democratic Republic of the",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("DR Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Democratic Republic of the Congo",'Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace("Dem. Rep. of the Congo",'Democratic Republic of the Congo (the)')



df['Country Name'] = df['Country Name'].replace("Cote d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Côte d’Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cote dIvoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Cōte d'Ivoire","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Ivory Coast","Côte d'Ivoire")
df['Country Name'] = df['Country Name'].replace("Dem. People's Rep. of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Democratic People's Republic of Korea","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("Korea, Dem. People's Rep.","Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].replace("North Korea","Democratic People's Republic of Korea (the)")

df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
df['Country Name'] = df['Country Name'].replace("Eswatini (Kingdom of)",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Swaziland",'Eswatini')
df['Country Name'] = df['Country Name'].replace("Faröe Islands",'Faroe Islands')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
df['Country Name'] = df['Country Name'].replace("Georgia (Country)",'Georgia')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
df['Country Name'] = df['Country Name'].replace("Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep. of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Rep.)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea (Republic of)",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Korea, South",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("South Korea",'Republic of Korea (the)')
df['Country Name'] = df['Country Name'].replace("Republic of Korea",'Republic of Korea (the)')

df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
df['Country Name'] = df['Country Name'].replace("Morroco",'Morocco')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].replace("Niger",'Niger (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
df['Country Name'] = df['Country Name'].replace("West Bank and Gaza",'State of Palestine (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
df['Country Name'] = df['Country Name'].replace("Republic of the Congo",'Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
df['Country Name'] = df['Country Name'].replace("Russia",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].replace("Russian Federation",'Russian Federation (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Sudan.*$)', "Sudan (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")

df['Country Name'] = df['Country Name'].replace("UAE",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("U.A.E",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace("United Arab Emirates",'United Arab Emirates (the)')
df['Country Name'] = df['Country Name'].replace('United Kingdom','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('UK','United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("Great Britain",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace("United Kingdom of Great Britain and Northern Ireland",'United Kingdom of Great Britain and Northern Ireland (the)')
df['Country Name'] = df['Country Name'].replace('Vietnam','Viet Nam')
df['Country Name'] = df['Country Name'].replace('United States','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('USA','United States of America (the)')
df['Country Name'] = df['Country Name'].replace('United States of America','United States of America (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
df['Country Name'] = df['Country Name'].replace('Sint Maarten','Saint Martin')
df['Country Name'] = df['Country Name'].replace('St. Martin (French part)','Saint Martin (French Part)')
df['Country Name'] = df['Country Name'].replace('Sint Maarten (Dutch part)','Saint Martin (Dutch Part)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
df['Country Name'] = df['Country Name'].replace('Congo, Democratic Republic','Democratic Republic of the Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo, Rep.','Congo (the)')
df['Country Name'] = df['Country Name'].replace('Congo (Rep.)','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")

df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
df['Country Name'] = df['Country Name'].replace('Eq. Guinea','Equatorial Guinea')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
df['Country Name'] = df['Country Name'].replace('C.A. Republic','Central African Republic (the)')
df['Country Name'] = df['Country Name'].replace('Ant.& Barb.','Antigua and Barbuda')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
df['Country Name'] = df['Country Name'].replace('Domin. Rep.','Dominican Republic (the)')
df['Country Name'] = df['Country Name'].replace('Dominica (Commonwealth of)','Dominica')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
df['Country Name'] = df['Country Name'].replace('R. of Congo','Congo (the)')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
df['Country Name'] = df['Country Name'].replace('Curacao','Curaçao')
df['Country Name'] = df['Country Name'].replace('Reunion','Réunion')
df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

<ipython-input-6-069e4143d8bc>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bahamas.*$)', 'Bahamas (the)')
<ipython-input-6-069e4143d8bc>:29: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r"(^.*Côte d'Ivoire.*$)", "Côte d'Ivoire")
<ipython-input-6-069e4143d8bc>:37: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Czech.*$)', 'Czechia')
<ipython-input-6-069e4143d8bc>:38: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Dominican Re.*$)', 'Dominican Republic (the)')
<ipython-input-6-069e4143d8bc>:39: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hong Kong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-6-069e4143d8bc>:40: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Hongkong.*$)', 'China, Hong Kong Special Administrative Region')
<ipython-input-6-069e4143d8bc>:44: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Gambia.*$)', 'Gambia (the)')
<ipython-input-6-069e4143d8bc>:46: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Iran.*$)', 'Iran (Islamic Republic of)')
<ipython-input-6-069e4143d8bc>:51: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, Rep.*$)', 'Republic of Korea (the)')
<ipython-input-6-069e4143d8bc>:56: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kyrgyz.*$)', 'Kyrgyzstan')
<ipython-input-6-069e4143d8bc>:57: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lao.*$)', "Lao People's Democratic Republic (the)")
<ipython-input-6-069e4143d8bc>:58: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macao.*$)', "China, Macao Special Administrative Region")
<ipython-input-6-069e4143d8bc>:59: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macau.*$)', "China, Macao Special Administrative Region")
<ipython-input-6-069e4143d8bc>:60: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Micronesia.*$)', "Micronesia (Federated States of)")
<ipython-input-6-069e4143d8bc>:61: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Moldova.*$)', "Republic of Moldova (the)")
<ipython-input-6-069e4143d8bc>:63: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Nepal.*$)', "Nepal")
<ipython-input-6-069e4143d8bc>:64: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-6-069e4143d8bc>:66: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Macedonia.*$)', "North Macedonia")
<ipython-input-6-069e4143d8bc>:67: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*New Ze.*$)', "New Zealand")
<ipython-input-6-069e4143d8bc>:68: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Palestin.*$)', "State of Palestine (the)")
<ipython-input-6-069e4143d8bc>:70: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Panama.*$)', "Panama")
<ipython-input-6-069e4143d8bc>:71: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Philippines.*$)', "Philippines (the)")
<ipython-input-6-069e4143d8bc>:73: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Myanmar.*$)', "Myanmar")
<ipython-input-6-069e4143d8bc>:74: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Puerto Rico.*$)', "Puerto Rico")
<ipython-input-6-069e4143d8bc>:77: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Slovak.*$)', "Slovakia")
<ipython-input-6-069e4143d8bc>:78: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Sudan.*$)', "Sudan (the)")
<ipython-input-6-069e4143d8bc>:79: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Syria.*$)', "Syrian Arab Republic (the)")
<ipython-input-6-069e4143d8bc>:80: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*São Tomé.*$)', "Sao Tome and Principe")
<ipython-input-6-069e4143d8bc>:81: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taiwan.*$)', "Taiwan")
<ipython-input-6-069e4143d8bc>:82: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Taipei.*$)', "Taiwan")
<ipython-input-6-069e4143d8bc>:83: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tanzania.*$)', "United Republic of Tanzania (the)")
<ipython-input-6-069e4143d8bc>:84: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Netherlands.*$)', "Netherlands (the)")
<ipython-input-6-069e4143d8bc>:97: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Virgin Islands.*$)', "United States Virgin Islands")
<ipython-input-6-069e4143d8bc>:98: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vatican.*$)', "Vatican")
<ipython-input-6-069e4143d8bc>:99: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Venezuela.*$)', "Venezuela (Bolivarian Republic of)")
<ipython-input-6-069e4143d8bc>:100: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Yemen.*$)', "Yemen")
<ipython-input-6-069e4143d8bc>:101: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Arab world.*$)', "Arab World")
<ipython-input-6-069e4143d8bc>:102: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*World.*$)', "World")
<ipython-input-6-069e4143d8bc>:103: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kitts and Nevis.*$)', "Saint Kitts and Nevis")
<ipython-input-6-069e4143d8bc>:104: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Lucia.*$)', "Saint Lucia")
<ipython-input-6-069e4143d8bc>:105: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Martin (French Part).*$)', "Saint Martin (French Part)")
<ipython-input-6-069e4143d8bc>:109: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent and the Grenadines.*$)', "Saint Vincent and the Grenadines")
<ipython-input-6-069e4143d8bc>:110: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Verde.*$)', "Cabo Verde")
<ipython-input-6-069e4143d8bc>:114: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Egypt.*$)', "Egypt")
<ipython-input-6-069e4143d8bc>:116: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Korea, D.*$)', "Democratic People's Republic of Korea (the)")
<ipython-input-6-069e4143d8bc>:117: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Tobago.*$)', "Trinidad and Tobago")
<ipython-input-6-069e4143d8bc>:118: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Timor-Leste.*$)', "Timor-Leste")
<ipython-input-6-069e4143d8bc>:119: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Emirates.*$)', "United Arab Emirates (the)")
<ipython-input-6-069e4143d8bc>:120: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Papua.*$)', "Papua New Guinea")
<ipython-input-6-069e4143d8bc>:121: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bissau.*$)', "Guinea-Bissau")
<ipython-input-6-069e4143d8bc>:123: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Burma.*$)', "Myanmar")
<ipython-input-6-069e4143d8bc>:126: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Bosnia.*$)', "Bosnia and Herzegovina")
<ipython-input-6-069e4143d8bc>:129: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*European Union.*$)', "European Union")
<ipython-input-6-069e4143d8bc>:131: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Principe.*$)', "Sao Tome and Principe")
<ipython-input-6-069e4143d8bc>:132: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Solomon.*$)', "Solomon Islands")
<ipython-input-6-069e4143d8bc>:133: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Vincent.*$)', "Saint Vincent and the Grenadines")
<ipython-input-6-069e4143d8bc>:136: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country Name'] = df['Country Name'].str.replace(r'(^.*Kosovo.*$)', "Kosovo (UNSCR 1244)")

In [7]:
#to_drop = ['Africa','Africa Eastern and Southern','Africa Western and Central']
#df = df[~df['Country Name'].isin(to_drop)]

In [8]:
sorted(df['Country Name'].unique().tolist())

['Afghanistan',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas (the)',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic (the)',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'China, Hong Kong Special Administrative Region',
 'China, Macao Special Administrative Region',
 'Colombia',
 'Comoros (the)',
 'Congo (the)',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czechia',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea (the)",
 'Democratic Republic of the Congo (the)',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic (the)',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia (the)',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo (UNSCR 1244)',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic (the)",
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (Federated States of)',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle income',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands (the)',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger (the)',
 'Nigeria',
 'North America',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines (the)',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico',
 'Qatar',
 'Republic of Korea (the)',
 'Republic of Moldova (the)',
 'Romania',
 'Russian Federation (the)',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (Dutch Part)',
 'Saint Martin (French Part)',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'Spain',
 'Sri Lanka',
 'State of Palestine (the)',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan (the)',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic (the)',
 'Taiwan',
 'Tajikistan',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates (the)',
 'United Kingdom of Great Britain and Northern Ireland (the)',
 'United Republic of Tanzania (the)',
 'United States Virgin Islands',
 'United States of America (the)',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [9]:
# Test All

In [10]:
df = df[['Country Name','HRAssociation','agg_score','count_source','agg_score_wt']]
df.to_csv('../../score/HR_country_scores/All.csv',index = False)

In [11]:
### Average Scores by Pillars and Subpillars

In [12]:
df = pd.read_csv('../../score/HR_country_scores/All.csv')
df = df[['Country Name','HRAssociation','agg_score','count_source']]
df

,Country Name,HRAssociation,agg_score,count_source
0,Saint Martin (French Part),Access,6.000000,1
1,Kosovo (UNSCR 1244),Access,6.000000,1
2,Saint Martin (Dutch Part),Access,6.000000,1
3,United States Virgin Islands,Access,6.000000,1
4,"China, Macao Special Administrative Region",Access,6.000000,1
...,...,...,...,...
355,Niger (the),Access,0.948270,6
356,Equatorial Guinea,Access,0.865922,1
357,Sudan (the),Access,0.847372,6
358,Somalia,Access,0.732777,2
359,Eritrea,Access,0.703857,1

In [13]:
# When normalizing country names, some entries in subpillar will be duplicated, to resolve this, the method is to multiple
# the agg_score with count_source and then divided them by the total number of source to get the average
df['total_agg'] = df['agg_score']*df['count_source']
df

,Country Name,HRAssociation,agg_score,count_source,total_agg
0,Saint Martin (French Part),Access,6.000000,1,6.000000
1,Kosovo (UNSCR 1244),Access,6.000000,1,6.000000
2,Saint Martin (Dutch Part),Access,6.000000,1,6.000000
3,United States Virgin Islands,Access,6.000000,1,6.000000
4,"China, Macao Special Administrative Region",Access,6.000000,1,6.000000
...,...,...,...,...,...
355,Niger (the),Access,0.948270,6,5.689621
356,Equatorial Guinea,Access,0.865922,1,0.865922
357,Sudan (the),Access,0.847372,6,5.084230
358,Somalia,Access,0.732777,2,1.465553
359,Eritrea,Access,0.703857,1,0.703857

In [14]:
# Eliminate all duplicate Subpillar entries by aveerage them all
score_source = df.groupby(['Country Name','HRAssociation']).agg({'total_agg':'sum','count_source':'sum'}).reset_index()
score_source['final_score'] = score_source['total_agg']/score_source['count_source']
score_source.rename(columns = {'final_score': 'agg_score'}, inplace = True)
df = score_source

In [15]:
#calculate the total average of sub-pillar score for each country
total_score =  df.groupby(['Country Name']).agg({'agg_score':'mean'}).reset_index()
total_score['HRAssociation'] = np.nan 
total_score = total_score[['Country Name','HRAssociation','agg_score']]
total_score.head(15)

                   Country Name  HRAssociation  agg_score
0                   Afghanistan            NaN   2.401000
1   Africa Eastern and Southern            NaN   3.182033
2    Africa Western and Central            NaN   3.567071
3                       Albania            NaN   4.507324
4                       Algeria            NaN   4.394477
5                       Andorra            NaN   1.200000
6                        Angola            NaN   3.592299
7           Antigua and Barbuda            NaN   1.200000
8                     Argentina            NaN   4.823534
9                       Armenia            NaN   4.514613
10                        Aruba            NaN   6.000000
11                    Australia            NaN   5.235208
12                      Austria            NaN   5.538192
13                   Azerbaijan            NaN   3.783876
14                Bahamas (the)            NaN   5.647917

In [16]:
product = pd.concat([total_score, df], axis=0)
product.rename(columns={'agg_score':'Score'}, inplace=True)
product = product[['Country Name','HRAssociation','Score']]

In [17]:
product.to_csv('../../score/HR_country_scores/Total_Scores.csv',index = False)