In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
### Score Aggregating by Subpillars

In [3]:
# get list of files in scores folder
scores = os.listdir('../subpillar_score/')
scores

df = pd.concat([pd.read_csv('../subpillar_score/{}'.format(s)) for s in scores])

In [4]:
df['Country Name'] = df['Country Name'].str.strip()
df['Country Name'] = df['Country Name'].str.strip('**')
df['Country Name'] = df['Country Name'].str.strip('*')
df['Country Name'] = df['Country Name'].str.strip('*')

# Replace as much code with country names as much as possible
df['Country Name'] = df['Country Name'].replace('UZ','Uzbekistan')
df['Country Name'] = df['Country Name'].replace('Vietnam','Viet Nam')
df['Country Name'] = df['Country Name'].replace('United States','United States of America')
df['Country Name'] = df['Country Name'].replace('UK','United Kingdom')
df['Country Name'] = df['Country Name'].replace('-',np.nan)
df['Country Name'] = df['Country Name'].replace('0.03',np.nan)
df = df.dropna()

In [5]:
sorted(df['Country Name'].unique().tolist())

['Afghanistan',
 'Africa',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Ant.& Barb.',
 'Antigua and Barbuda',
 'Arab World',
 'Arab world',
 'Argentina',
 'Armenia',
 'Aruba',
 'Asia Pacific',
 'Australia',
 'Austria',
 'Azerbaijan',
 'B:',
 'Bahamas',
 'Bahamas, The',
 'Bahrain',
 'Bahrain (Kingdom of)',
 'Bangladesh',
 'Bangladesh Chittagong',
 'Bangladesh Dhaka',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belgium Estonia',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bolivia (Plurinational State of)',
 'Bolivia, Plurinational State of',
 'Bosnia & Herz.',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brazil Rio de Janeiro',
 'Brazil São Paulo',
 'British Virgin Islands',
 'Brunei',
 'Brunei Darussalam',
 'Bulgaria',
 'Bulgaria (Rep.)',
 'Burkina Faso',
 'Burma',
 'Burundi',
 'C.A. Republic',
 'CAN',
 'CHE',
 'CIS',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Rep.',
 'Central African Republic',
 'Central America',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 "China (People's Rep.)",
 'China Beijing',
 'China Shanghai',
 'China, Hong Kong SAR',
 'Chinese Taipei',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo (Brazzaville)',
 'Congo (Democratic Republic of the)',
 'Congo (Rep. of the)',
 'Congo (Rep.)',
 'Congo, Dem. Rep.',
 'Congo, Democratic Republic',
 'Congo, Rep.',
 'Congo, The Democratic Republic of the',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Cote dIvoire',
 'Croatia',
 'Cuba',
 'Curacao',
 'Curaçao',
 'Cyprus',
 'Czech Rep.',
 'Czech Republic',
 'Czechia',
 "Côte d'Ivoire",
 "Côte d'Ivoire (Rep.)",
 'Côte d’Ivoire',
 "Cōte d'Ivoire",
 'D:',
 'DEU',
 'DR Congo',
 'Data extracted on 10 Sep 2021 15:04 UTC (GMT) from OECD.Stat',
 "Dem. People's Rep. of Korea",
 'Dem. Rep. of the Congo',
 "Democratic People's Republic of Korea",
 'Democratic Republic of Congo',
 'Democratic Republic of the Congo',
 'Denmark',
 'Developing',
 'Djibouti',
 'Domin. Rep.',
 'Dominica',
 'Dominica (Commonwealth of)',
 'Dominican Rep.',
 'Dominican Republic',
 'ESP',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'East and South Asia',
 'Eastern Africa',
 'Eastern Europe and Central Asia',
 'Ecuador',
 'Egypt',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Eq. Guinea',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Eswatini (Kingdom of)',
 'Ethiopia',
 'Euro area',
 'Europe',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'Europe (other)',
 'European Union',
 'European Union (27 countries)',
 'European Union (28 countries)',
 'FIN',
 'Faeroe Islands',
 'Falkland Islands',
 'Faroe Islands',
 'Faröe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Guiana',
 'French Polynesia',
 'G.-Bissau',
 'Gabon',
 'Gambia',
 'Gambia, The',
 'Georgia',
 'Georgia (Country)',
 'Germany',
 'Germany France',
 'Ghana',
 'Gibraltar',
 'Great Britain',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'High income: OECD',
 'High-income Countries',
 'Holy See',
 'Honduras',
 'Honduras (Rep.)',
 'Hong Kong',
 'Hong Kong (China)',
 'Hong Kong (SAR)',
 'Hong Kong S.A.R. of China',
 'Hong Kong SAR, China',
 'Hong Kong, China',
 'Hong Kong, China (SAR)',
 'Hongkong, China',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'IRL',
 'ITA',
 'Iceland',
 'India',
 'India Delhi',
 'India Mumbai',
 'Indonesia',
 'Indonesia Jakarta',
 'Indonesia Surabaya',
 'Iran',
 'Iran (Islamic Rep.)',
 'Iran (Islamic Republic of)',
 'Iran, Islamic Rep.',
 'Iran, Islamic Republic of',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Japan Osaka',
 'Japan Tokyo',
 'Jersey',
 'Jordan',
 'KOR',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea',
 'Korea (Rep. of)',
 'Korea (Rep.)',
 'Korea (Republic of)',
 'Korea, DPR',
 "Korea, Dem. People's Rep.",
 'Korea, Dem. Rep.',
 'Korea, Rep.',
 'Korea, Republic of',
 'Korea, South',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Kyrgyzstan',
 'Lao P.D.R.',
 'Lao PDR',
 "Lao People's Dem. Rep.",
 "Lao People's Democratic Republic",
 'Laos',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latin America and the Caribbean',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Legend:',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Low-income Countries',
 'Lower middle income',
 'Lower-middle-income Countries',
 'Luxembourg',
 'Macao',
 'Macao SAR, China',
 'Macao, China',
 'Macau',
 'Macau (SAR)',
 'Macedonia',
 'Macedonia, FYR',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Mexico Mexico City',
 'Mexico Monterrey',
 'Micronesia',
 'Micronesia (Federated States of)',
 'Micronesia, Fed. Sts.',
 'Middle Africa',
 'Middle East',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle East and North Africa',
 'Middle income',
 'Moldova',
 'Moldova (Republic of)',
 'Moldova, Republic of',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Morroco',
 'Mozambique',
 'Myanmar',
 'NZL',
 'Namibia',
 'Nauru',
 'Nepal',
 'Nepal (Republic of)',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'New Zeland',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Nigeria Kano',
 'Nigeria Lagos',
 'Niue',
 'North America',
 'North Cyprus',
 'North Korea',
 'North Macedonia',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Not classified',
 'OECD members',
 'Oceania',
 'Oman',
 'Other Asia & Pacific',
 'Other CIS',
 'Other Caribbean',
 'Other Middle East',
 'Other Northern Africa',
 'Other South America',
 'Other Southern Africa',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Pakistan Karachi',
 'Pakistan Lahore',
 'Palau',
 'Palestine',
 'Palestine, State of',
 'Palestinian Territories',
 'Panama',
 'Panama (Rep.)',
 'Papua N.G.',
 'Papua New Guinea',
 'Paraguay',
 'Personal Card',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico',
 'Puerto Rico (U.S.)',
 'Qatar',
 'R. of Congo',
 'Republic of Korea',
 'Republic of Moldova',
 'Republic of the Congo',
 'Republic of the Union of Myanmar',
 'Reunion',
 'Romania',
 'Russia',
 'Russian Federation',
 'Russian Federation Moscow',
 'Russian Federation Saint Petersburg',
 'Rwanda',
 'S.T.&Principe',
 'Saint Christopher (St. Kitts) and Nevis',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Slovakia',
 'Slovenia',
 'Small Island Developing States',
 'Small states',
 'Solomon Isl.',
 'Solomon Islands',
 'Somalia',
 'South & Central America',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Martin (French part)',
 'St. Vincent & ...',
 'St. Vincent and the Grenadines',
 'State of Palestine',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Syrian Arab Rep.',
 'Syrian Arab Republic',
 'São Tomé and Principe',
 'São Tomé and Príncipe',
 'Taiwan',
 'Taiwan Province of China',
 'Taiwan, China',
 'Taiwan, province of China',
 'Tajikistan',
 'Tanzania',
 'Tanzania (United Rep.)',
 'Tanzania (United Republic of)',
 'Tanzania, United Republic of',
 'Thailand',
 'The Bahamas',
 'The Gambia',
 'The Netherlands',
 'Timor-Leste',
 'Timor-Leste (Dem. Rep.)',
 'Togo',
 'Tokelau',
 'Tonga',
 'Tr.&Tobago',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'U.A.E',
 'UA Emirates',
 'UAE',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Republic of Tanzania',
 'United States Los Angeles',
 'United States New York City',
 'United States Virgin Islands',
 'United States of America',
 'Unknown',
 'Upper middle income',
 'Upper-middle-income Countries',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Vatican City',
 'Venezuela',
 'Venezuela (Bolivarian Rep. of)',
 'Venezuela (Bolivarian Rep.)',
 'Venezuela (Bolivarian Republic of)',
 'Venezuela, RB',
 'Viet Nam',
 'Virgin Islands (U.S.)',
 'Virgin Islands, U.S.',
 'Wallis and Futuna',
 'West Bank and Gaza',
 'Western Africa',
 'Western Sahara',
 'World',
 'Worldwide',
 'Yemen',
 'Yemen, Arab Republic',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe']

In [6]:
# Test Uzbekistan

In [7]:
uzb = df[(df['Country Name'] == 'Uzbekistan')]
uzb
uzb.to_csv('../country_scores/Uzbekistan.csv',index = False)

In [8]:
# Test Japan

In [9]:
jp = df[(df['Country Name'] == 'Japan')]
jp
jp.to_csv('../country_scores/Japan.csv',index = False)

In [10]:
# Test Germany

In [11]:
gr = df[(df['Country Name'] == 'Germany')]
gr
gr.to_csv('../country_scores/Germany.csv',index = False)

In [12]:
# Test France

In [13]:
fr = df[(df['Country Name'] == 'France')]
fr
fr.to_csv('../country_scores/France.csv',index = False)

In [14]:
# Test Sweden

In [15]:
sw = df[(df['Country Name'] == 'Sweden')]
sw
sw.to_csv('../country_scores/Sweden.csv',index = False)

In [16]:
# Test Viet Nam

In [17]:
vn = df[(df['Country Name'] == 'Viet Nam')]
vn
vn.to_csv('../country_scores/Viet Nam.csv',index = False)

In [18]:
# Test Armenia

In [19]:
am = df[(df['Country Name'] == 'Armenia')]
am
am.to_csv('../country_scores/Armenia.csv',index = False)

In [20]:
# Test USA

In [21]:
usa = df[(df['Country Name'] == 'United States of America')]
usa
usa.to_csv('../country_scores/USA.csv',index = False)

In [22]:
# Test All

In [23]:
df = df[['Country Name','Pillar','Sub-Pillar','agg_score','count_source','agg_score_wt']]
df.to_excel('../country_scores/All.xlsx',index = False)

In [24]:
### Score Aggregating by Individual Indicators

In [25]:
# get list of files in scores folder
scores = os.listdir('../indicator_scores/')
scores
df = pd.concat([pd.read_csv('../indicator_scores/{}'.format(s)) for s in scores])    
df = df[['Sub-Pillar','Indicator','Country Name','Year','data_col','new_rank_score','higher_is_better']]
df

,Sub-Pillar,Indicator,Country Name,Year,data_col,new_rank_score,higher_is_better
0,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Germany,2018.0,18.2,1.910,True
1,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Japan,2018.0,20.3,2.015,True
2,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",United States,2018.0,18.0,1.900,True
3,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",United Kingdom,2018.0,19.8,1.990,True
4,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Australia,2018.0,16.1,1.805,True
...,...,...,...,...,...,...,...
200,Ambition,SDG Index,Sub-Saharan Africa,2019.0,51.9,3.595,True
201,Ambition,SDG Index,Low-income Countries,2019.0,51.0,3.550,True
202,Ambition,SDG Index,Lower-middle-income Countries,2019.0,60.1,4.005,True
203,Ambition,SDG Index,Upper-middle-income Countries,2019.0,70.8,4.540,True
204,Ambition,SDG Index,High-income Countries,2019.0,78.1,4.905,True

In [26]:
df['Country Name'] = df['Country Name'].str.strip()
df['Country Name'] = df['Country Name'].str.strip('**')
df['Country Name'] = df['Country Name'].str.strip('*')
df['Country Name'] = df['Country Name'].str.strip('*')

# Replace as much code with country names as much as possible
df['Country Name'] = df['Country Name'].replace('UZ','Uzbekistan')
df['Country Name'] = df['Country Name'].replace('Vietnam','Viet Nam')
df['Country Name'] = df['Country Name'].replace('United States','United States of America')
df['Country Name'] = df['Country Name'].replace('UK','United Kingdom')
df = df.dropna()

In [27]:
df.insert(0,'Pillar','')
df.loc[(df['Sub-Pillar'] == 'Connectivity Technology') | (df['Sub-Pillar'] == 'Innovation Ecosystem'), 'Pillar'] = 'Infrastructure'
df.loc[(df['Sub-Pillar'] == 'Financing Incentives') | (df['Sub-Pillar'] == 'Technology Adoption') | (df['Sub-Pillar'] == 'Startup Environment'), 'Pillar'] = 'Business'
df.loc[(df['Sub-Pillar'] == 'Data Exchange') | (df['Sub-Pillar'] == 'Digital Legal Identity') | (df['Sub-Pillar'] == 'Digital Payments'), 'Pillar'] = 'Foundations'
df.loc[(df['Sub-Pillar'] == 'Capabilities') | (df['Sub-Pillar'] == 'Digital Public Services') | (df['Sub-Pillar'] == 'Funding and procurement') | (df['Sub-Pillar'] == 'Leadership and coordination'), 'Pillar'] = 'Government'
df.loc[(df['Sub-Pillar'] == 'Culture') | (df['Sub-Pillar'] == 'Digital Literacy Skills') | (df['Sub-Pillar'] == 'Digital Wellbeing')| (df['Sub-Pillar'] == 'Usage and ownership'), 'Pillar'] = 'People'
df.loc[(df['Sub-Pillar'] == 'Cybersecurity') | (df['Sub-Pillar'] == 'Ethical Standards'), 'Pillar'] = 'Regulation'
df.loc[(df['Sub-Pillar'] == 'Ambition'), 'Pillar'] = 'Strategy'

df

D:\Apps\Anaconda\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,Pillar,Sub-Pillar,Indicator,Country Name,Year,data_col,new_rank_score,higher_is_better
0,Business,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Germany,2018.0,18.2,1.910,True
1,Business,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Japan,2018.0,20.3,2.015,True
2,Business,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",United States of America,2018.0,18.0,1.900,True
3,Business,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",United Kingdom,2018.0,19.8,1.990,True
4,Business,Technology Adoption,"Cloud Services (Spend, IT Forecast Data)",Australia,2018.0,16.1,1.805,True
...,...,...,...,...,...,...,...,...
200,Strategy,Ambition,SDG Index,Sub-Saharan Africa,2019.0,51.9,3.595,True
201,Strategy,Ambition,SDG Index,Low-income Countries,2019.0,51.0,3.550,True
202,Strategy,Ambition,SDG Index,Lower-middle-income Countries,2019.0,60.1,4.005,True
203,Strategy,Ambition,SDG Index,Upper-middle-income Countries,2019.0,70.8,4.540,True
204,Strategy,Ambition,SDG Index,High-income Countries,2019.0,78.1,4.905,True

In [28]:
# For all country
df = df[['Country Name','Year','Pillar','Sub-Pillar','Indicator','data_col','new_rank_score','higher_is_better']]
df.to_excel('../country_scores/All_Indicator.xlsx',index = False)

In [29]:
uzb = df[(df['Country Name'] == 'Uzbekistan')]
uzb

uzb.to_csv('../country_scores/Uzbekistan_Indicator.csv',index = False)

In [30]:
jp = df[(df['Country Name'] == 'Japan')]
jp

jp.to_csv('../country_scores/Japan_Indicator.csv',index = False)

In [31]:
vn = df[(df['Country Name'] == 'Viet Nam')]
vn

vn.to_csv('../country_scores/Viet Nam_Indicator.csv',index = False)

In [32]:
am = df[(df['Country Name'] == 'Armenia')]
am = am.dropna(subset=['data_col'])

am.to_csv('../country_scores/Armenia_Indicator.csv',index = False)

In [33]:
usa = df[(df['Country Name'] == 'United States of America')]
usa = usa.dropna(subset=['data_col'])

usa.to_csv('../country_scores/USA_Indicator.csv',index = False)